const fertileRiverValleyProvinceNames = [
    "Eldervale",
    "Rivermere",
    "Greenford",
    "Meadowshire",
    "Wilderbrook",
    "Valewood",
    "Willowdale",
    "Mossglen",
    "Evermead",
    "Springhollow",
    "Ferncroft",
    "Riverglen",
    "Meadowbrook",
    "Silvershire",
    "Sunsetvale",
    "Goldenfield",
    "Rivershire",
    "Lushmead",
    "Waterdown",
    "Riverglen",
    "Blossomford",
    "Verdantmead",
    "Shadewick",
    "Rosevale",
    "Briarwood",
    "Thornfield",
    "Greenshire",
    "Fertilehollow",
    "Riverstone",
    "Elmwood",
    "Windingbrook",
    "Flourishmead",
    "Wheatford",
    "Maplegrove",
    "Cloverfield",
    "Streamwood",
    "Harvestfield",
    "Emeraldmead",
    "Riversedge",
    "Sunvale",
    "Goldenbrook",
    "Fieldstone",
    "Springvale",
    "Verdantwood",
    "Greenway",
    "Brookhaven",
    "Riverfield",
    "Floralspring",
    "Bountifulgrove",
    "Valleyview",
    "Cornfield",
    "Springfield",
    "Verdantvale",
    "Willowspring",
    "Riverridge",
    "Meadowland",
    "Fertilefield",
    "Bloomingdale",
    "Sunsetgrove",
    "Mossvalley",
    "Goldenmead",
    "Fernvalley",
    "Riverton",
    "Blossomgrove",
    "Lushfield",
    "Shadybrook",
    "Springgrove",
    "Briarhollow",
    "Verdanthollow",
    "Riverpark",
    "Windingvale",
    "Riverwood",
    "Sunnyvale",
    "Greendale",
    "Flourishfield",
    "Crescentvale",
    "Shadyvale",
    "Harvestgrove",
    "Brookfield",
    "Springbank",
    "Meadowridge",
    "Riverhollow",
    "Lushvale",
    "Greenthorn",
    "Waterview",
    "Brookwood",
    "Sunrisevale",
    "Blossomvale",
    "Greenfield",
    "Waterbrook",
    "Meadowvale",
    "Sunsetfield",
    "Harvestbrook",
    "Riverdale",
    "Bountifulvale",
    "Verdantpark",
    "Brookshire",
    "Meadowview",
    "Riverblossom",
    "Sunvalley"
];

const highAltitudeIcyMountainProvinceNames = [
    "Frostpeak",
    "Winterhold",
    "Icewind",
    "Snowspire",
    "Frostvale",
    "Glacierford",
    "Icecliff",
    "Frostguard",
    "Snowdell",
    "Icemist",
    "Frostglen",
    "Snowspire",
    "Frostheim",
    "Wintercrest",
    "Icemeadow",
    "Snowdrift",
    "Frostmire",
    "Glacierhold",
    "Snowpeak",
    "Icehaven",
    "Frostfall",
    "Snowridge",
    "Icetooth",
    "Winterholm",
    "Frostvalley",
    "Glacierfall",
    "Snowguard",
    "Icemountain",
    "Frostrock",
    "Snowcliff",
    "Icevale",
    "Winterdale",
    "Frostbridge",
    "Snowkeep",
    "Icefort",
    "Frostbluff",
    "Snowhold",
    "Iceshire",
    "Winterfort",
    "Frostburn",
    "Snowhelm",
    "Iceridge",
    "Frostspire",
    "Snowreach",
    "Icestone",
    "Winterglen",
    "Frostvale",
    "Snowpeak",
    "Icefall",
    "Winterguard",
    "Frostblight",
    "Snowspire",
    "Iceclaw",
    "Winterrock",
    "Frostdell",
    "Snowwatch",
    "Icemeadow",
    "Winterfrost",
    "Frostward",
    "Snowbluff",
    "Icelake",
    "Winterpeak",
    "Frostwatch",
    "Snowfort",
    "Iceglen",
    "Winterspire",
    "Frostcliff",
    "Snowridge",
    "Icebridge",
    "Winterhold",
    "Frostguard",
    "Snowvale",
    "Icewatch",
    "Winterspire",
    "Frostholm",
    "Snowcrest",
    "Icemist",
    "Wintervalley",
    "Frosthearth",
    "Snowfield",
    "Icekeep",
    "Winterfrost",
    "Frostpeak",
    "Snowglen",
    "Icebridge",
    "Winterguard",
    "Frostvale",
    "Snowcliff",
    "Icemeadow",
    "Winterwatch",
    "Frostfort",
    "Snowspire",
    "Iceford",
    "Winterbluff",
    "Frostrock",
    "Snowhold",
    "Icefall",
    "Winterspire",
    "Frostguard",
    "Snowglen",
    "Icevalley"
];

const tropicalIslandProvinceNames = [
    "Isle of Eldoria",
    "Palmshaven",
    "Isle of Greenward",
    "Tropics of Avalon",
    "Isle of Verdan",
    "Palmkeep",
    "Isle of Brightwood",
    "Tropics of Elden",
    "Isle of Sunward",
    "Palmgrove",
    "Isle of Verdant",
    "Tropics of Briar",
    "Isle of Sunvale",
    "Palmdell",
    "Isle of Greenglen",
    "Tropics of Silversun",
    "Isle of Summerwind",
    "Palmwatch",
    "Isle of Blossom",
    "Tropics of Fairwind",
    "Isle of Greenfort",
    "Palmside",
    "Isle of Verdane",
    "Tropics of Goldleaf",
    "Isle of Sunwatch",
    "Palmstead",
    "Isle of Greenstone",
    "Tropics of Elmswood",
    "Isle of Summerfall",
    "Palmvalley",
    "Isle of Brightshore",
    "Tropics of Greenway",
    "Isle of Sunnyside",
    "Palmrock",
    "Isle of Greenwater",
    "Tropics of Fairleaf",
    "Isle of Sunport",
    "Palmdale",
    "Isle of Greenvale",
    "Tropics of Brightbay",
    "Isle of Summerfort",
    "Palmcliff",
    "Isle of Verdania",
    "Tropics of Goldcrest",
    "Isle of Sunnystone",
    "Palmisle",
    "Isle of Greenmeadow",
    "Tropics of Elmsreach",
    "Isle of Sunhaven",
    "Palmbrook",
    "Isle of Brightbay",
    "Tropics of Verdance",
    "Isle of Summerglen",
    "Palmwood",
    "Isle of Greenfield",
    "Tropics of Goldhaven",
    "Isle of Sunstone",
    "Palmglen",
    "Isle of Verdantwood",
    "Tropics of Brightcliff",
    "Isle of Greenridge",
    "Palmcove",
    "Isle of Greenport",
    "Tropics of Goldvale",
    "Isle of Summerwatch",
    "Palmgrove",
    "Isle of Greenhearth",
    "Tropics of Fairstone",
    "Isle of Sunrock",
    "Palmlake",
    "Isle of Greenthorn",
    "Tropics of Brightlake",
    "Isle of Sunreach",
    "Palmharbor",
    "Isle of Greenreach",
    "Tropics of Elmsford",
    "Isle of Summermead",
    "Palmshore",
    "Isle of Greenhill",
    "Tropics of Goldstone",
    "Isle of Sunfall",
    "Palmcliff",
    "Isle of Verdantis",
    "Tropics of Brightport",
    "Isle of Greenholm",
    "Palmspring",
    "Isle of Brightmead",
    "Tropics of Goldshore",
    "Isle of Summerport",
    "Palmlight",
    "Isle of Greencrest",
    "Tropics of Fairport",
    "Isle of Sunmeadow",
    "Palmguard",
    "Isle of Verdania",
    "Tropics of Brightguard",
    "Isle of Greenbluff",
    "Palmvalley",
    "Isle of Summercliff",
    "Tropics of Elmswatch"
];

const temperateForestProvinceNames = [
    "Elmswood",
    "Ferncroft",
    "Alderhall",
    "Briarwood",
    "Wolfswood",
    "Greenwold",
    "Mistvale",
    "Oakenshade",
    "Everspring",
    "Cedarwood",
    "Hawthornvale",
    "Whispering Pines",
    "Foxglove Grove",
    "Ravenwood",
    "Birchgrove",
    "Elderwild",
    "Maplewood",
    "Hartwood",
    "Shadowfen",
    "Ashenvale",
    "Glenwood",
    "Thornwood",
    "Frostwood",
    "Willowdale",
    "Silverwood",
    "Fernwood",
    "Cypress Grove",
    "Ironwood",
    "Driftwood",
    "Pinewood",
    "Hazelwood",
    "Woodhaven",
    "Forestford",
    "Mosswood",
    "Briarcliff",
    "Evergreen",
    "Thornfield",
    "Wolverton",
    "Brackenwood",
    "Rookwood",
    "Greenfield",
    "Foxwood",
    "Hemlock Hollow",
    "Whisperwood",
    "Ashwood",
    "Rowanwood",
    "Wyrmwood",
    "Thistledown",
    "Hawkwood",
    "Lynxwood",
    "Rosewood",
    "Shadowbrook",
    "Autumnwood",
    "Pinehurst",
    "Wolfpine",
    "Glenhaven",
    "Elkwood",
    "Greenthorn",
    "Bramblewood",
    "Fernwood",
    "Lindenwood",
    "Grimwood",
    "Woodgrove",
    "Thornwell",
    "Aspenwood",
    "Hollowgrove",
    "Elmshire",
    "Foxgrove",
    "Greenbriar",
    "Pinemarch",
    "Willowsmere",
    "Ravenmarch",
    "Hearthwood",
    "Mirkwood",
    "Springwood",
    "Brackenvale",
    "Wilderwood",
    "Ironbark",
    "Silverpine",
    "Alderbrook",
    "Darkwood",
    "Stagwood",
    "Greenwood",
    "Briarvale",
    "Fernshade",
    "Cedarvale",
    "Briarfen",
    "Greenhollow",
    "Mistwood",
    "Wolfsbane",
    "Oakheart",
    "Mossgrove",
    "Havenwood",
    "Thornfield",
    "Wyrmshade",
    "Hollowshade",
    "Ashenwood",
    "Willowshade",
    "Ravenfen"
];

const dryDesertProvinceNames = [
    "Sablecrag",
    "Dusthaven",
    "Sandspire",
    "Dunewatch",
    "Blightrock",
    "Aridhold",
    "Sunfall",
    "Parched Vale",
    "Ashenridge",
    "Desolate Plains",
    "Wasteland",
    "Bleakstone",
    "Scorchfield",
    "Sandwraith",
    "Witherford",
    "Sunblight",
    "Barren Sands",
    "Cragspire",
    "Dryreach",
    "Sunstorm",
    "Dustmere",
    "Gritstone",
    "Searing Expanse",
    "Wyrmsands",
    "Dunecrest",
    "Blaze Hollow",
    "Ashen Wastes",
    "Dustwind",
    "Sunstalker",
    "Parched Hollow",
    "Sandhold",
    "Dryland",
    "Blightvale",
    "Scorched Dunes",
    "Desertcliff",
    "Windblight",
    "Sable Sands",
    "Sunsear",
    "Dustfall",
    "Wastelands",
    "Dunebrook",
    "Bleak Haven",
    "Witherstone",
    "Blazecliff",
    "Aridstone",
    "Droughtford",
    "Sunscorch",
    "Parched Ridge",
    "Ashen Cliffs",
    "Dryrock",
    "Sunchar",
    "Scorchvale",
    "Blighted Sands",
    "Dunewatch",
    "Dustshadow",
    "Wastemere",
    "Sunstorm",
    "Sable Ridge",
    "Withercrest",
    "Grit Hollow",
    "Scorchwind",
    "Ashen Peak",
    "Dustspire",
    "Blightvale",
    "Sunfury",
    "Desertwind",
    "Dry Expanse",
    "Sableblight",
    "Searing Cliffs",
    "Dustwraith",
    "Sunbleak",
    "Barrencliff",
    "Droughtvale",
    "Scorchfield",
    "Ashen Sands",
    "Sunscour",
    "Parched Hills",
    "Wasteland",
    "Desertspine",
    "Blazehaven",
    "Drybluff",
    "Dustburn",
    "Bleak Dunes",
    "Sableford",
    "Wyrmspire",
    "Sunseeker",
    "Scorch Plains",
    "Dunevale",
    "Witherwind",
    "Ashenwaste",
    "Blight Ridge",
    "Sunstalk",
    "Dustwaste",
    "Parchedland",
    "Gritstone",
    "Desolate Sands",
    "Blazewind",
    "Dryspine"
];

const coastalProvinceNames = [
    "Seawatch",
    "Harborview",
    "Brinecliff",
    "Saltshore",
    "Windward",
    "Wavecrest",
    "Bayguard",
    "Tidewater",
    "Seamere",
    "Ocean's Edge",
    "Brinyhaven",
    "Waverock",
    "Seabreeze",
    "Anchorfall",
    "Seastone",
    "Harborwind",
    "Shorewatch",
    "Tideshore",
    "Seaspray",
    "Wavescar",
    "Bayridge",
    "Saltmarsh",
    "Seacliff",
    "Oceanveil",
    "Brinefort",
    "Windtide",
    "Seafort",
    "Waveridge",
    "Seawind",
    "Harbormouth",
    "Shoreford",
    "Tidestone",
    "Seashell",
    "Wavewatch",
    "Bayview",
    "Saltcliffe",
    "Seapoint",
    "Oceancrest",
    "Brineview",
    "Windshore",
    "Seawood",
    "Waverun",
    "Seamouth",
    "Harborfield",
    "Shorevale",
    "Tidevale",
    "Seascar",
    "Waveguard",
    "Baypoint",
    "Saltwatch",
    "Seaford",
    "Oceanside",
    "Brinewind",
    "Windcliff",
    "Seastone",
    "Wavecrest",
    "Seamere",
    "Harborcliff",
    "Shoreward",
    "Tideview",
    "Seawatch",
    "Waveshield",
    "Bayhold",
    "Saltrock",
    "Seabrook",
    "Oceanhold",
    "Brineward",
    "Windfort",
    "Seafield",
    "Waveford",
    "Seashore",
    "Harborreach",
    "Shorefall",
    "Tidecrest",
    "Seacliff",
    "Wavehaven",
    "Baystone",
    "Saltvale",
    "Seawind",
    "Oceanshield",
    "Brinestone",
    "Windview",
    "Seaguard",
    "Waveview",
    "Seaview",
    "Harborstone",
    "Shoremouth",
    "Tidefort",
    "Seabreeze",
    "Waveside",
    "Baymouth",
    "Saltport",
    "Seapoint",
    "Oceanscar",
    "Brinewatch",
    "Windridge",
    "Seafront",
    "Waveport"
];

const lakeProvinceNames = [
    "Lakewood",
    "Everspring Lake",
    "Silvermere",
    "Lakehall",
    "Mistwater",
    "Brackenlake",
    "Lakestead",
    "Hawthornmere",
    "Ravenlake",
    "Alderwater",
    "Briarmere",
    "Lakeglen",
    "Ashenmere",
    "Greenlake",
    "Havenmere",
    "Elderlake",
    "Swanmere",
    "Elmswater",
    "Frostlake",
    "Whispering Lake",
    "Hartlake",
    "Shadewater",
    "Foxmere",
    "Eaglelake",
    "Lakemist",
    "Wolfwater",
    "Thornmere",
    "Springlake",
    "Lakestone",
    "Fernwater",
    "Greymere",
    "Oakenlake",
    "Hollowmere",
    "Wilderlake",
    "Lakemount",
    "Rivermere",
    "Grimmere",
    "Maplelake",
    "Laketon",
    "Wolfsbane Lake",
    "Lakemont",
    "Stormmere",
    "Heathlake",
    "Emberlake",
    "Lakemead",
    "Whisperlake",
    "Lakethorn",
    "Darkmere",
    "Fairlake",
    "Lakemoor",
    "Glenmere",
    "Mosslake",
    "Lakemarch",
    "Shadewater",
    "Lakemist",
    "Mirthlake",
    "Thornlake",
    "Lakestone",
    "Hollowlake",
    "Lakemere",
    "Frostmere",
    "Lakemist",
    "Ravenmere",
    "Lakestead",
    "Laketon",
    "Lakemont",
    "Moorlake",
    "Lakethorn",
    "Springmere",
    "Lakemeadow",
    "Hawklake",
    "Laketon",
    "Lakemoor",
    "Lakemist",
    "Lakethorn",
    "Stormlake",
    "Lakemere",
    "Lakemount",
    "Lakestone",
    "Wildermere",
    "Lakemist",
    "Hollowlake",
    "Lakemarch",
    "Fairmere",
    "Laketon",
    "Lakemount",
    "Lakemead",
    "Glenlake",
    "Lakemoor",
    "Shademere",
    "Lakemist",
    "Lakethorn",
    "Lakemead",
    "Lakestone",
    "Lakemere",
    "Lakemount",
    "Lakemist",
    "Laketon",
    "Wilderlake"
];

const bayProvinceNames = [
    "Stormbay",
    "Golden Bay",
    "Silver Cove",
    "Wolfsbay",
    "Dragon's Bay",
    "Seaglass Bay",
    "Eagle Bay",
    "Brimstone Bay",
    "Fairwind Bay",
    "Crimson Bay",
    "Tidewater Bay",
    "Saltmarsh Bay",
    "Whispering Bay",
    "Mossbay",
    "Brine Bay",
    "Crescent Bay",
    "Seaforth Bay",
    "Ironcliff Bay",
    "Lionsbay",
    "Emerald Bay",
    "Moonbay",
    "Whalebone Bay",
    "Mistbay",
    "Shimmering Bay",
    "Frostbay",
    "Azure Bay",
    "Sunset Bay",
    "Haven Bay",
    "Brightwater Bay",
    "Crowsbay",
    "Shadow Bay",
    "Raven Bay",
    "Gale Bay",
    "Thornbay",
    "Windward Bay",
    "Seafall Bay",
    "Hightide Bay",
    "Oakenshore Bay",
    "Dawn Bay",
    "Sunrise Bay",
    "Glimmer Bay",
    "Wavecrest Bay",
    "Stormwatch Bay",
    "Duskmere Bay",
    "Whitecap Bay",
    "Darkwater Bay",
    "Firebay",
    "Frostfall Bay",
    "Seabreeze Bay",
    "Driftwood Bay",
    "Goldenwave Bay",
    "Brightwave Bay",
    "Seashell Bay",
    "Lighthouse Bay",
    "Stormcloud Bay",
    "Seafarer's Bay",
    "Iron Bay",
    "Sunfall Bay",
    "Twilight Bay",
    "Windwhisper Bay",
    "Eldermere Bay",
    "Silverlight Bay",
    "Duskwave Bay",
    "Windward Bay",
    "Stormvale Bay",
    "Seastorm Bay",
    "Glimmering Bay",
    "Frostwave Bay",
    "Seafarer Bay",
    "Stormhold Bay",
    "Tidecrest Bay",
    "Windfall Bay",
    "Sunrise Bay",
    "Mistveil Bay",
    "Seabound Bay",
    "Blazing Bay",
    "Shimmer Bay",
    "Crag Bay",
    "Tempest Bay",
    "Whisper Bay",
    "Moonlight Bay",
    "Sunbeam Bay",
    "Oaken Bay",
    "Dragon Bay",
    "Crescent Bay",
    "Ironshore Bay",
    "Salt Bay",
    "Thorn Bay",
    "Whalefall Bay",
    "Stormlight Bay",
    "Galeshore Bay",
    "Brighthaven Bay",
    "Brinewave Bay",
    "Windfury Bay",
    "Sunstorm Bay",
    "Whitewave Bay",
    "Seawatch Bay",
    "Azurewave Bay",
    "Stormfury Bay",
    "Silverwind Bay",
    "Goldenfall Bay",
    "Shimmerwave Bay"
];

const islandProvinceNames = [
    "Isle of Eldoria",
    "Dragon's Isle",
    "Isle of Thorns",
    "Silvercrest Isle",
    "Wolfsbane Isle",
    "Isle of Avalon",
    "Stormhaven Isle",
    "Brimstone Isle",
    "Isle of Shadows",
    "Isle of Whispers",
    "Seaglass Isle",
    "Isle of Frost",
    "Ravencliff Isle",
    "Isle of Emerald",
    "Isle of Mist",
    "Isle of Everspring",
    "Ironwood Isle",
    "Isle of Dawn",
    "Isle of Secrets",
    "Isle of Ravens",
    "Isle of Sunlight",
    "Isle of Storms",
    "Isle of Crag",
    "Isle of Shimmer",
    "Isle of Brambles",
    "Isle of Moonlight",
    "Isle of Glimmer",
    "Isle of Wind",
    "Isle of Azure",
    "Isle of Oaks",
    "Isle of Twilight",
    "Isle of Gold",
    "Isle of Fire",
    "Isle of Mists",
    "Isle of Winter",
    "Isle of Spring",
    "Isle of Waves",
    "Isle of the Ancients",
    "Isle of Dragons",
    "Isle of the Lost",
    "Isle of the Forgotten",
    "Isle of the Brave",
    "Isle of the Free",
    "Isle of the Sea",
    "Isle of the Sky",
    "Isle of the Wind",
    "Isle of the Sun",
    "Isle of the Moon",
    "Isle of the Stars",
    "Isle of the Storm",
    "Isle of the Frost",
    "Isle of the Fire",
    "Isle of the Waves",
    "Isle of the Everspring",
    "Isle of the Ravens",
    "Isle of the Oaks",
    "Isle of the Shadows",
    "Isle of the Whispering Winds",
    "Isle of the Crimson Tide",
    "Isle of the Golden Sun",
    "Isle of the Silver Moon",
    "Isle of the Crystal Waters",
    "Isle of the Hidden Treasure",
    "Isle of the Wandering Spirits",
    "Isle of the Eternal Flame",
    "Isle of the Shimmering Sands",
    "Isle of the Thunderous Roar",
    "Isle of the Silent Echo",
    "Isle of the Sacred Grove",
    "Isle of the Wailing Winds",
    "Isle of the Enchanted Forest",
    "Isle of the Mystic Veil",
    "Isle of the Celestial Light",
    "Isle of the Darkwood",
    "Isle of the Frostbite",
    "Isle of the Nightingale",
    "Isle of the Solstice",
    "Isle of the Morning Dew",
    "Isle of the Fiery Dawn",
    "Isle of the Icy Peaks",
    "Isle of the Verdant Fields",
    "Isle of the Crystal Peaks",
    "Isle of the Sapphire Sea",
    "Isle of the Emerald Glade",
    "Isle of the Tempest",
    "Isle of the Thunder",
    "Isle of the Gale",
    "Isle of the Zephyr",
    "Isle of the Horizon",
    "Isle of the Sunset",
    "Isle of the Dawnlight",
    "Isle of the Dusk",
    "Isle of the Breakwater",
    "Isle of the Sirens",
    "Isle of the Tides",
    "Isle of the Cliffs",
    "Isle of the Echo",
    "Isle of the Silent Seas",
    "Isle of the Beacon"
];

const highlandValleyProvinceNames = [
    "Hawkridge Valley",
    "Silverhills",
    "Riverstone Vale",
    "Highpeak Valley",
    "Brackenridge",
    "Windy Hollow",
    "Raven's Crest",
    "Stonebrook Valley",
    "Elmsridge",
    "Briarvale",
    "Mistvale",
    "Eagle's Nest",
    "Stormhill",
    "Greystone Vale",
    "Thornridge",
    "Oakenshade",
    "Evergreen Valley",
    "Ironridge",
    "Glenhaven",
    "Foxhollow",
    "Hawkwood Vale",
    "Rivershadow",
    "Thornhills",
    "Wolfswood Valley",
    "Frostbrook",
    "Hearthridge",
    "Elderspring",
    "Stoneridge",
    "Windwhisper Valley",
    "Wolf's Hollow",
    "Falcon's Nest",
    "Rivermist",
    "Havenridge",
    "Shadowvale",
    "Ashenbrook",
    "Stormvale",
    "Greenthorn Valley",
    "Stag's Hollow",
    "Griffonridge",
    "Frostwood Vale",
    "Eagleridge",
    "Brightvale",
    "Mossy Hollow",
    "Highbrook Valley",
    "Thornwood",
    "Brimstone Vale",
    "Windward Hollow",
    "Oakhaven",
    "Ravenwood",
    "Hawk's Rest",
    "Greenvale",
    "Wolfpine Valley",
    "Silverbrook",
    "Mistwood Vale",
    "Rivervale",
    "Briarhollow",
    "Elderwood",
    "Ironbrook",
    "Stormridge",
    "Thornvale",
    "Windpeak Valley",
    "Ravenshadow",
    "Hawthorn Valley",
    "Oakenshield",
    "Evervale",
    "Glenwood Vale",
    "Foxridge",
    "Falconridge",
    "Riverglen",
    "Stonehaven",
    "Wolf's Vale",
    "Frosthollow",
    "Hearthwood",
    "Eldergrove",
    "Shadowbrook",
    "Greystone Valley",
    "Stormhollow",
    "Highwind Vale",
    "Bramblebrook",
    "Mistwood Valley",
    "Rivershadow Vale",
    "Thornpeak",
    "Windward Vale",
    "Raven's Hollow",
    "Hawkwood",
    "Greenbrook Valley",
    "Wolf's Ridge",
    "Silverhollow",
    "Eaglemont",
    "Brightwood",
    "Stoneridge Vale",
    "Thorncliff",
    "Windcrest",
    "Oakendell",
    "Greenshade Valley",
    "Frostvale",
    "Rivermist Vale",
    "Elderhollow",
    "Hawk's Vale",
    "Stonecrest"
];

const denseForestProvinceNames = [
    "Eldergrove",
    "Whisperwood",
    "Darkwood",
    "Thornwood",
    "Ravenwood",
    "Shadowfen",
    "Mistwood",
    "Briarwood",
    "Greenwild",
    "Wolfwood",
    "Ironwood",
    "Ashenvale",
    "Oakenshade",
    "Brackenwood",
    "Foxwood",
    "Hawthorne",
    "Elmswood",
    "Cedarwood",
    "Hartwood",
    "Thornvale",
    "Everwood",
    "Grimwood",
    "Hollowgrove",
    "Silverwood",
    "Stormwood",
    "Blackwood",
    "Ravenholt",
    "Wilderwood",
    "Stormgrove",
    "Glenwood",
    "Greenvale",
    "Frostwood",
    "Everspring",
    "Shadowgrove",
    "Woodhaven",
    "Fernwood",
    "Rivengrove",
    "Bramblewood",
    "Mosswood",
    "Thistledown",
    "Wolfshadow",
    "Oakengrove",
    "Ironholt",
    "Shadewood",
    "Maplewood",
    "Windwood",
    "Highwood",
    "Thornfield",
    "Foxgrove",
    "Hartgrove",
    "Ashwood",
    "Silverholt",
    "Rookwood",
    "Greenthorn",
    "Eldershade",
    "Pinewood",
    "Darkgrove",
    "Shadowwood",
    "Ravenwild",
    "Hawkridge",
    "Elmgrove",
    "Oakwood",
    "Wolfgrove",
    "Brackenholt",
    "Briarvale",
    "Evergreen",
    "Cedarvale",
    "Thornholt",
    "Foxvale",
    "Greenholt",
    "Ashenwood",
    "Mistgrove",
    "Shadewood",
    "Frostvale",
    "Hollowwood",
    "Grimvale",
    "Wolfswood",
    "Eaglewood",
    "Stormvale",
    "Elderwood",
    "Shadowvale",
    "Brackenvale",
    "Wolfvale",
    "Thistlegrove",
    "Oakenshade",
    "Elmsvale",
    "Pinegrove",
    "Hawkridge",
    "Thornwild",
    "Windvale",
    "Hartwild",
    "Foxwood",
    "Rookgrove",
    "Cedarwild",
    "Ironvale",
    "Mossgrove",
    "Greenthicket",
    "Stormshadow",
    "Evergrove"
];

const coastalMountainProvinceNames = [
    "Stormcrag",
    "Seacliff Peaks",
    "Brinemount",
    "Waverock Heights",
    "Frostbay Mountains",
    "Ironshore Cliffs",
    "Windcrag",
    "Tidepeak",
    "Seastone Ridge",
    "Wavecrest Heights",
    "Saltspire",
    "Stormwatch Mountains",
    "Seaview Peaks",
    "Wavemist Ridge",
    "Brinecliff",
    "Stormpeak",
    "Seastorm Mountains",
    "Windpeak Cliffs",
    "Tidecrag",
    "Seafrost Peaks",
    "Waveguard Heights",
    "Saltcrag",
    "Stormbay Mountains",
    "Seawatch Ridge",
    "Brinepeak",
    "Windrock",
    "Tideshore Cliffs",
    "Seafoam Heights",
    "Wavecrest Mountains",
    "Saltrock",
    "Stormgale Peaks",
    "Seaspray Ridge",
    "Brinestone",
    "Windwhisper Cliffs",
    "Tidewatch Heights",
    "Seacliff Mountains",
    "Wavebluff",
    "Saltmist Peaks",
    "Stormshore Ridge",
    "Seabreeze Heights",
    "Brinegale",
    "Windcliff",
    "Tidestorm Cliffs",
    "Seasworn Peaks",
    "Wavegale Mountains",
    "Saltwave Ridge",
    "Stormwrath Heights",
    "Seamist Cliffs",
    "Brinebay Peaks",
    "Windcrest Ridge",
    "Tideview Heights",
    "Seasong Mountains",
    "Wavewrath Cliffs",
    "Saltwhisper Peaks",
    "Stormwave Ridge",
    "Seastone Heights",
    "Brinewatch Cliffs",
    "Windbay Peaks",
    "Tidecrest Ridge",
    "Seafury Heights",
    "Wavegale Mountains",
    "Saltbay Cliffs",
    "Stormgale Ridge",
    "Seafrost Heights",
    "Brinewave Peaks",
    "Windshore Cliffs",
    "Tidewrath Ridge",
    "Seafoam Heights",
    "Wavebay Mountains",
    "Saltcrest Cliffs",
    "Stormwhisper Peaks",
    "Seafury Ridge",
    "Brinestone Heights",
    "Windwrath Cliffs",
    "Tidegale Ridge",
    "Seasworn Heights",
    "Wavewrath Peaks",
    "Saltwave Cliffs",
    "Stormcrest Ridge",
    "Seamist Heights",
    "Brinecrest Peaks",
    "Windview Cliffs",
    "Tidecrest Heights",
    "Seafoam Peaks",
    "Wavegale Ridge",
    "Saltstorm Heights",
    "Stormgale Cliffs",
    "Seafrost Peaks",
    "Brinewhisper Ridge",
    "Windcrest Heights",
    "Tideview Cliffs",
    "Seasong Peaks",
    "Wavecrest Ridge",
    "Saltbay Heights",
    "Stormwhisper Cliffs",
    "Seastorm Ridge",
    "Brinewrath Heights",
    "Windwrath Peaks",
    "Tidegale Cliffs",
    "Seastone Ridge"
];

const frozenTundraProvinceNames = [
    "Frostheim",
    "Icereach",
    "Glacierford",
    "Winterfall",
    "Frostvale",
    "Snowdrift",
    "Icewind Dale",
    "Frostcliff",
    "Coldspire",
    "Frostglen",
    "Snowbound",
    "Icetooth",
    "Frostbrook",
    "Icecrown",
    "Winterglen",
    "Frostmire",
    "Glacierpeak",
    "Snowpeak",
    "Icestone",
    "Frostward",
    "Iceclaw",
    "Winterhold",
    "Frostcrag",
    "Snowstorm",
    "Icewatch",
    "Frostvale",
    "Glacierhold",
    "Snowfall",
    "Icemeadow",
    "Frostwraith",
    "Icefort",
    "Winterridge",
    "Frostfield",
    "Snowhelm",
    "Icebrook",
    "Frostwhisper",
    "Glacierfall",
    "Snowvale",
    "Iceblight",
    "Frostbite",
    "Icepeak",
    "Wintershade",
    "Frostfire",
    "Snowshadow",
    "Icehearth",
    "Frostpine",
    "Glacierpass",
    "Snowfort",
    "Iceward",
    "Frostlake",
    "Icevale",
    "Winterward",
    "Frostrock",
    "Snowgale",
    "Icestream",
    "Frostfury",
    "Icegrove",
    "Wintermoor",
    "Frostwood",
    "Snowvale",
    "Icebluff",
    "Frostglade",
    "Glacierwood",
    "Snowfrost",
    "Icetundra",
    "Frostfall",
    "Icehaven",
    "Winterfrost",
    "Frostbay",
    "Snowthorn",
    "Icepine",
    "Frostspray",
    "Glacierhaven",
    "Snowgrove",
    "Iceblaze",
    "Frosthollow",
    "Iceshade",
    "Winterwraith",
    "Frostpine",
    "Snowgrove",
    "Iceforge",
    "Frostwrath",
    "Snowwhisper",
    "Iceshadow",
    "Frostguard",
    "Glacierguard",
    "Snowspire",
    "Icepass",
    "Frostspire",
    "Icemoor",
    "Winterspire",
    "Frostthorn",
    "Snowguard",
    "Icewind",
    "Frostsong",
    "Iceshield",
    "Winterblade",
    "Frostblight",
    "Snowpass",
    "Iceshield",
    "Frostveil",
    "Glacierveil",
    "Snowpine"
];

const majorRiverDeltaProvinceNames = [
    "Rivermouth",
    "Deltaford",
    "Wetlands Reach",
    "Marshwater",
    "Riversend",
    "Bayoufield",
    "Mossy Delta",
    "Rivermarsh",
    "Tidewater Delta",
    "Swampland",
    "Riversbend",
    "Floodplain",
    "Delta Marsh",
    "Riverhaven",
    "Wetland Hollow",
    "Rivershade",
    "Bogwater",
    "Riversend Delta",
    "Mirefield",
    "Delta Haven",
    "Marshford",
    "Riverflow",
    "Tidepool",
    "Riversedge",
    "Mossland",
    "Rivertide",
    "Floodlands",
    "Delta Reach",
    "Riverveil",
    "Wetlands Edge",
    "Riverswell",
    "Bayou Vale",
    "Marshland",
    "Riverdelta",
    "Wetlandsford",
    "Riversfield",
    "Bogside",
    "River Hollow",
    "Mirevale",
    "Deltafield",
    "Rivertide Marsh",
    "Marshlight",
    "Riversglen",
    "Wetland Bay",
    "Rivershade Delta",
    "Floodglen",
    "Delta Shores",
    "Riverbend Marsh",
    "Swampwood",
    "Rivermead",
    "Wetland Valley",
    "Riverswell Delta",
    "Bayougrove",
    "Marshfield",
    "River Hollow Delta",
    "Wetland Reach",
    "Rivertide Haven",
    "Bog Vale",
    "Riverford",
    "Delta Vale",
    "Riverspool",
    "Floodhaven",
    "Wetland Hollow Delta",
    "Riversreach",
    "Mossyfield",
    "River Edge",
    "Swampfield",
    "Riverlight",
    "Wetlandsend",
    "Rivertide Edge",
    "Marshglen",
    "Riversbay",
    "Deltaflow",
    "Riverbend Hollow",
    "Floodwood",
    "Delta Haven Marsh",
    "Riveredge",
    "Wetlands Reach",
    "Riversvale",
    "Bayoufield Delta",
    "Marshhaven",
    "Rivermeadow",
    "Wetland Marsh",
    "Riversbend Hollow",
    "Bogfield",
    "Rivershade Vale",
    "Floodbay",
    "Deltafield Marsh",
    "Riversglen Delta",
    "Marshbay",
    "Riverglen",
    "Wetlandsfield",
    "Riverswell Hollow",
    "Bayoufield Haven",
    "Marshlight Delta",
    "Riverglow",
    "Wetland Vale",
    "Riverspool Delta",
    "Delta Reach Hollow"
];

const fertilePlateauProvinceNames = [
    "Highfield",
    "Greenridge",
    "Riversheaf",
    "Farmlands Reach",
    "Verdant Rise",
    "Plowshare Plateau",
    "Riverside Fields",
    "Suncrest",
    "Goldenplain",
    "Hearthland",
    "Highmeadow",
    "Riverbend Plains",
    "Greenthorn Plateau",
    "Eldergreen",
    "Wheatland Heights",
    "Fertile Vale",
    "Riversheath",
    "Verdant Hollow",
    "Harvestcrest",
    "Ridgefield",
    "Greensward",
    "Riverfall",
    "Sunvale",
    "Golden Ridge",
    "Highgrove",
    "Plowfield",
    "Rivercrest",
    "Greenbriar",
    "Elderfield",
    "Wheatland Rise",
    "Fertile Haven",
    "Riversreach",
    "Verdant Ridge",
    "Harvestfield",
    "Greenhill",
    "Rivermeadow",
    "Sunridge",
    "Goldfield",
    "Highplain",
    "Plowshare Ridge",
    "Riversvale",
    "Greenhaven",
    "Elderhearth",
    "Wheatcrest",
    "Fertile Glen",
    "Riversbend",
    "Verdant Heights",
    "Harvestbrook",
    "Greenfield",
    "Riverglen",
    "Sunmeadow",
    "Goldengrove",
    "Highvale",
    "Plowridge",
    "Rivershade",
    "Greenshire",
    "Eldercrest",
    "Wheatfield",
    "Fertile Heights",
    "Riversheath Vale",
    "Verdantfield",
    "Harvest Haven",
    "Greenridge Vale",
    "Riverbrook",
    "Sungrove",
    "Goldenvale",
    "Highgrove Plains",
    "Plowhearth",
    "Riversfall",
    "Greenvale",
    "Eldermeadow",
    "Wheatland Vale",
    "Fertile Ridge",
    "Rivershade Heights",
    "Verdant Plains",
    "Harvestvale",
    "Greencrest",
    "Riverfield",
    "Suncrest Heights",
    "Goldenfield",
    "Highmeadow Ridge",
    "Plowvalley",
    "Riversridge",
    "Greenglen",
    "Eldergrove",
    "Wheatland Fields",
    "Fertilegrove",
    "Riversheath Plateau",
    "Verdant Grove",
    "Harvest Heights",
    "Greenridge Plains",
    "Riverglen Heights",
    "Sungrove Plateau",
    "Goldengrove Fields",
    "Highvale Plains",
    "Plowheath",
    "Riversbend Heights"
];

const coastalWetlandProvinceNames = [
    "Marshlight Cove",
    "Brinehaven",
    "Saltmarsh Reach",
    "Tidewater Fen",
    "Mistbay",
    "Brackwater Shore",
    "Wetlands End",
    "Mudflats",
    "Bayou Bend",
    "Fogwater",
    "Tideswamp",
    "Brinebay",
    "Saltmire",
    "Watershade",
    "Mudshore",
    "Bogswell",
    "Tidehaven",
    "Brinehollow",
    "Saltfen",
    "Waveswamp",
    "Mudbay",
    "Bogshore",
    "Fogshore",
    "Tidesmire",
    "Brinefield",
    "Saltwater Flats",
    "Waterfen",
    "Mirehaven",
    "Bayouwater",
    "Foggy Marsh",
    "Brinemire",
    "Saltflats",
    "Tidebog",
    "Mudmire",
    "Waterswamp",
    "Bogbend",
    "Tidefield",
    "Brinegrove",
    "Saltbog",
    "Watershade Cove",
    "Mudlight",
    "Bogshade",
    "Fogbend",
    "Tidemire",
    "Brineflats",
    "Saltlight",
    "Waterbog",
    "Mirebay",
    "Bayoushore",
    "Fogmire",
    "Brinewaters",
    "Saltshade",
    "Tidegrove",
    "Mudfield",
    "Watershade Flats",
    "Bogwater",
    "Tideflats",
    "Brinecove",
    "Saltbend",
    "Waterfield",
    "Mireflats",
    "Bayoufen",
    "Fogwater Cove",
    "Brinebog",
    "Saltshade Flats",
    "Tidehaven Shore",
    "Mudshade",
    "Watersmire",
    "Boglight",
    "Fogfield",
    "Tidefield Flats",
    "Brineshore",
    "Saltgrove",
    "Watermire",
    "Mirelight",
    "Bayoushade",
    "Fogbog",
    "Brinefen",
    "Saltwater Flats",
    "Tidewater Flats",
    "Mudgrove",
    "Watersfield",
    "Bogfield Flats",
    "Tidegrove Shore",
    "Brinewater",
    "Saltwater Shore",
    "Waterlight",
    "Miregrove",
    "Bayoulight",
    "Fogshade",
    "Brinefield Flats",
    "Saltgrove Shore",
    "Tidebog Flats",
    "Mudbog",
    "Watershade Shore",
    "Bogwater Flats",
    "Tidefield Shore",
    "Brinefield Shore"
];

const subtropicalIslandWithJungleProvinceNames = [
    "Emerald Isle",
    "Dragon's Rest",
    "Verdant Isle",
    "Sunshadow",
    "Mystic Isle",
    "Jungle Haven",
    "Greenwater",
    "Whispering Isle",
    "Eldergrove",
    "Moonshadow",
    "Grove Isle",
    "Wildwood",
    "Serpent's Isle",
    "Ferncliff",
    "Vinewood",
    "Shadewood",
    "Stormgrove",
    "Lushwood",
    "Eagle's Nest",
    "Tanglewood",
    "Silverleaf",
    "Palmshade",
    "Brambles",
    "Jade Isle",
    "Frostwood",
    "Glade Isle",
    "Sunstone",
    "Ravenwood",
    "Wolf's Haven",
    "Elmswood",
    "Goldenleaf",
    "Hawkwood",
    "Thornwood",
    "Highgrove",
    "Shadowfen",
    "Briarwood",
    "Oakenshade",
    "Rivershade",
    "Sunvale",
    "Greenbriar",
    "Ashwood",
    "Brightwood",
    "Sunhaven",
    "Thornvale",
    "Everwood",
    "Mossgrove",
    "Wilderwood",
    "Hawk's Rest",
    "Greenshade",
    "Riverwood",
    "Silvershade",
    "Darkwood",
    "Wolfsbane",
    "Greenthorn",
    "Fernwood",
    "Elderwood",
    "Maplewood",
    "Windwood",
    "Hollowgrove",
    "Stormwood",
    "Feywood",
    "Lynwood",
    "Wildgrove",
    "Whisperwood",
    "Hawthorne",
    "Mystwood",
    "Thistlewood",
    "Brackenwood",
    "Ivywood",
    "Cypress Isle",
    "Drake's Isle",
    "Pinewood",
    "Willowgrove",
    "Greenvale",
    "Shadowgrove",
    "Foxwood",
    "Evergreen",
    "Silvergrove",
    "Wolf's Wood",
    "Eaglewood",
    "Hawkridge",
    "Ironwood",
    "Greenglen",
    "Dragon's Isle",
    "Sunshadow Isle",
    "Vinemoor",
    "Darkgrove",
    "Elmsvale",
    "Ravenglen",
    "Sablewood",
    "Moonglade",
    "Oakwood",
    "Windgrove",
    "Shadowvale",
    "Sunshadow Bay",
    "Frostgrove",
    "Ravenclaw",
    "Glenwood",
    "Windvale"
];

const alpineForestProvinceNames = [
    "Frostwood",
    "Highgrove",
    "Ravenpine",
    "Ironwood",
    "Frostpine",
    "Winterwood",
    "Snowshade",
    "Coldwood",
    "Icegrove",
    "Frosthaven",
    "Everpine",
    "Windwood",
    "Frostcliff",
    "Glacierwood",
    "Frostvale",
    "Shadowpine",
    "Winterpine",
    "Frostglen",
    "Icewood",
    "Frostpeak",
    "Snowgrove",
    "Icehaven",
    "Frostfall",
    "Everfrost",
    "Frostrock",
    "Winterglen",
    "Frostwild",
    "Coldgrove",
    "Frostshade",
    "Snowwood",
    "Windpine",
    "Frostspire",
    "Frostfield",
    "Wintershade",
    "Snowhaven",
    "Frostvale",
    "Icepeak",
    "Frostpine",
    "Frostbrook",
    "Glaciergrove",
    "Frosthill",
    "Wintergrove",
    "Frostcrest",
    "Icefield",
    "Frosthill",
    "Snowpine",
    "Everice",
    "Frostywood",
    "Winterfall",
    "Frostforest",
    "Coldpeak",
    "Snowcliff",
    "Windgrove",
    "Frostheath",
    "Icegrove",
    "Frostmount",
    "Snowfield",
    "Frostrock",
    "Glacierpine",
    "Frosthaven",
    "Wintercliff",
    "Snowforest",
    "Evercliff",
    "Frostpeak",
    "Iceshade",
    "Frostcliff",
    "Snowspire",
    "Windcliff",
    "Frostpine",
    "Wintercrest",
    "Snowfall",
    "Frosthearth",
    "Icepine",
    "Frostspire",
    "Winterhearth",
    "Coldspire",
    "Snowglen",
    "Frostwind",
    "Icepeak",
    "Frostvale",
    "Glacierhearth",
    "Frostpine",
    "Wintervale",
    "Snowhill",
    "Windpeak",
    "Frostshade",
    "Iceforest",
    "Frostyheath",
    "Snowhill",
    "Frostywood",
    "Glacierheath",
    "Frostfield",
    "Winterpeak",
    "Snowhearth",
    "Everpine",
    "Frostwood",
    "Icemount",
    "Frostcrest"
];

const coastalDesertWithOasisProvinceNames = [
    "Oasis of Eldur",
    "Mirage Shores",
    "Brineholm Dunes",
    "Sandfall Oasis",
    "Golden Brine",
    "Sunspire Cove",
    "Tidewater Oasis",
    "Sands of Mirith",
    "Oasis of Thalor",
    "Lumin Dunes",
    "Briar Oasis",
    "Seawind Desert",
    "Brimstone Shores",
    "Dunes of Auriel",
    "Saltwind Oasis",
    "Stormsand Bay",
    "Oasis of Calad",
    "Sunlit Dunes",
    "Azure Oasis",
    "Oasis of Bryndor",
    "Tidecrest Dunes",
    "Glimmering Sands",
    "Oasis of Eldara",
    "Brinewatch",
    "Desert of Vynor",
    "Oasis of Myra",
    "Sunshade Dunes",
    "Oasis of Enara",
    "Brineshade",
    "Dunes of Aran",
    "Silver Oasis",
    "Brinecliff",
    "Desert of Altar",
    "Oasis of Zethar",
    "Mirage Bay",
    "Sunrise Oasis",
    "Oasis of Thrain",
    "Tidefall Dunes",
    "Gleaming Sands",
    "Oasis of Lyra",
    "Brinemire",
    "Desert of Serin",
    "Oasis of Theron",
    "Suncrest Dunes",
    "Oasis of Elara",
    "Saltwhisper Oasis",
    "Brineveil",
    "Desert of Thar",
    "Oasis of Wynd",
    "Mirageshade",
    "Golden Oasis",
    "Brinefire Dunes",
    "Oasis of Eldwyn",
    "Tidewell Sands",
    "Shimmering Oasis",
    "Oasis of Ryn",
    "Brinestone",
    "Desert of Zephyr",
    "Oasis of Elaria",
    "Sunblight Dunes",
    "Oasis of Thorne",
    "Brinestorm",
    "Dunes of Solara",
    "Azurecliff Oasis",
    "Brinewood",
    "Desert of Krynn",
    "Oasis of Zalor",
    "Miragecrest",
    "Sunflare Dunes",
    "Oasis of Vael",
    "Saltreach",
    "Desert of Rylan",
    "Oasis of Nyr",
    "Glimmersands",
    "Brinestorm",
    "Desert of Tyra",
    "Oasis of Jor",
    "Sunward Dunes",
    "Oasis of Brith",
    "Brinehollow",
    "Dunes of Arya",
    "Oasis of Elden",
    "Goldenshade Oasis",
    "Brinestone Bay",
    "Desert of Xylor",
    "Oasis of Galad",
    "Miragefall",
    "Sunspire Sands",
    "Oasis of Lyth",
    "Saltspire",
    "Desert of Vyrr",
    "Oasis of Zain",
    "Glimmering Dunes",
    "Brinereach",
    "Desert of Vor",
    "Oasis of Aric",
    "Sunveil Sands",
    "Oasis of Draen"
];

const riverCrossingMountainProvinceNames = [
    "Rivermount",
    "Stonecross Peaks",
    "Ironford Mountains",
    "Rivercrest",
    "Stormridge",
    "Twinriver Pass",
    "Bridgemount",
    "Frostcross",
    "Highwater Peaks",
    "Glaciercross",
    "Thunderforge",
    "Eagle's Crossing",
    "Dragon's Ford",
    "Riverforge",
    "Silverpass",
    "Ironridge",
    "Stonebridge",
    "Raven's Crossing",
    "Frostgate",
    "Windcross Peaks",
    "Wolf's Crossing",
    "Elderforge",
    "Rivershadow",
    "Thorncross",
    "Brightwater Peaks",
    "Stormcross",
    "Frostbridge",
    "Dragon's Crossing",
    "Thunderpass",
    "Grimcross",
    "Silvercross",
    "Riverpeak",
    "Ironcross",
    "Stonepass",
    "Wolf's Ford",
    "Stormbridge",
    "Frostpass",
    "Ravenpass",
    "Highforge",
    "Eagle's Ford",
    "Windforge",
    "Brightcross",
    "Rivengate",
    "Glacierpass",
    "Thornforge",
    "Ravenbridge",
    "Ironpeak",
    "Riversgate",
    "Stormpeak",
    "Elderpass",
    "Twinriver Forge",
    "Wolfpass",
    "Grimbridge",
    "Rivenshadow",
    "Dragon's Gate",
    "Brightforge",
    "Elderbridge",
    "Thunderforge Peaks",
    "Rivermount Pass",
    "Stonegate",
    "Ironbridge",
    "Silvergate",
    "Thornridge",
    "Brightpass",
    "Rivershadow Peaks",
    "Eagle's Pass",
    "Windbridge",
    "Stormforge",
    "Glacierforge",
    "Frostford",
    "Twinriver Ridge",
    "Wolfbridge",
    "Ravenforge",
    "Highcross",
    "Thundergate",
    "Stonecross Ridge",
    "Ironshadow",
    "Silverforge",
    "Brightwater Ridge",
    "Grimforge",
    "Rivergate",
    "Thornpass",
    "Stormgate",
    "Frostpeak",
    "Glaciergate",
    "Elderwater",
    "Rivenshadow Peaks",
    "Dragon's Pass",
    "Windpass",
    "Twinriver Heights",
    "Brightshadow",
    "Ravenpeak",
    "Thornshadow",
    "Grimgate",
    "Eagle's Gate",
    "Stormridge Pass",
    "Rivermount Heights"
];

const wetlandAdjacentToForestProvinceNames = [
    "Mossfen",
    "Shadowmire",
    "Eldermarsh",
    "Wyrdwood Bog",
    "Thornswamp",
    "Briarfen",
    "Mistwood Mire",
    "Brackenmarsh",
    "Fenwood",
    "Whispering Bog",
    "Ravenfen",
    "Greenmire",
    "Frostwood Swamp",
    "Hollowfen",
    "Darkwood Marsh",
    "Evershade Bog",
    "Murkwood Mire",
    "Grimfen",
    "Silverwood Marsh",
    "Wolfswamp",
    "Ashenfen",
    "Greymire",
    "Bramblebog",
    "Shadowfen",
    "Fernwood Swamp",
    "Elderglen Bog",
    "Thornmire",
    "Wildwood Marsh",
    "Hawkfen",
    "Ravenmire",
    "Everfen",
    "Brackenbog",
    "Mosswood Swamp",
    "Wyrdmarsh",
    "Grimwood Mire",
    "Murkfen",
    "Elderswamp",
    "Hollowmarsh",
    "Silverfen",
    "Whisperfen",
    "Ravenwood Bog",
    "Mistywood Swamp",
    "Greenfen",
    "Thornwood Mire",
    "Everswamp",
    "Ashenmarsh",
    "Shadowwood Bog",
    "Darkfen",
    "Wolffen",
    "Fernmire",
    "Eldermarsh Bog",
    "Hollowfen",
    "Ravenwood Swamp",
    "Grimfen",
    "Brackenmire",
    "Mistwood Fen",
    "Wildfen",
    "Hawkmarsh",
    "Evermire",
    "Greenwood Bog",
    "Whispermire",
    "Briarwood Swamp",
    "Silvermarsh",
    "Mossfen",
    "Shadowmire Bog",
    "Thornmarsh",
    "Ashenwood Mire",
    "Wolfswamp Fen",
    "Elderglen Swamp",
    "Fernfen",
    "Ravenmarsh",
    "Hollowbog",
    "Darkwood Mire",
    "Everswamp Fen",
    "Grimwood Bog",
    "Whisperwood Swamp",
    "Silvermire",
    "Murkfen",
    "Brackenwood Swamp",
    "Greenmire",
    "Shadowfen Bog",
    "Bramblemarsh",
    "Mistywood Fen",
    "Thornfen",
    "Ravenwood Mire",
    "Wildwood Fen",
    "Evermarsh",
    "Hawkfen",
    "Briarfen Swamp",
    "Elderswamp Bog",
    "Greenwood Mire",
    "Whispermire Fen",
    "Mosswood Bog",
    "Silverwood Fen",
    "Murkfen Bog",
    "Brackenmarsh Fen",
    "Darkfen",
    "Wyrdwood Fen"
];

const highlandWithMultipleRiversProvinceNames = [
    "Riverpeak",
    "Three Rivers Hills",
    "Highland Waters",
    "Twin Falls Highland",
    "Stoneridge Rivers",
    "Elderridge Waters",
    "Windriver Hills",
    "Highflow Peaks",
    "Thunderriver Highland",
    "Rivershadow Ridge",
    "Ravenriver Heights",
    "Stormriver Hills",
    "Silverstream Highlands",
    "Eaglebrook Peaks",
    "Frostflow Highland",
    "Brightriver Ridge",
    "Hawkstream Heights",
    "Riverspire",
    "Shadowbrook Highlands",
    "Rivenglen Peaks",
    "Threestream Hills",
    "Rivermist Heights",
    "Highbrook Falls",
    "Threewaters Highland",
    "Stonespring Ridge",
    "Wolfriver Peaks",
    "Rivendale Heights",
    "Hollowbrook Highlands",
    "Thunderridge Rivers",
    "Brightstream Peaks",
    "Hawkridge Waters",
    "Silverbrook Highland",
    "Rivercliff Heights",
    "Highfalls Waters",
    "Twinrivers Ridge",
    "Rivervale Heights",
    "Stormbrook Peaks",
    "Frostbrook Hills",
    "Brightwater Highlands",
    "Elderstream Peaks",
    "Shadowriver Heights",
    "Hawkriver Falls",
    "Rivershade Peaks",
    "Brightbrook Highland",
    "Windstream Heights",
    "Silverfalls Peaks",
    "Highspring Rivers",
    "Stoneriver Heights",
    "Froststream Highland",
    "Eagleriver Peaks",
    "Riversong Heights",
    "Brightwater Falls",
    "Hawkbrook Heights",
    "Ravenbrook Peaks",
    "Thunderriver Highlands",
    "Elderspring Heights",
    "Brightfalls Peaks",
    "Hollowspring Rivers",
    "Rivershadow Heights",
    "Highwater Peaks",
    "Stonestream Highland",
    "Twinbrook Heights",
    "Silverriver Falls",
    "Stormstream Peaks",
    "Windbrook Heights",
    "Riverspire Peaks",
    "Brightspring Highland",
    "Threerivers Peaks",
    "Rivermist Highlands",
    "Eagleridge Heights",
    "Rivenglen Waters",
    "Froststream Peaks",
    "Brightcliff Highland",
    "Ravenstream Heights",
    "Stormspring Peaks",
    "Rivershadow Falls",
    "Silverbrook Waters",
    "Hawkridge Heights",
    "Brightbrook Peaks",
    "Elderriver Heights",
    "Riversong Peaks",
    "Windriver Falls",
    "Silverstream Waters",
    "Hollowbrook Heights",
    "Rivendale Peaks",
    "Thunderridge Waters",
    "Brightfalls Heights",
    "Hawkbrook Peaks",
    "Rivershade Heights",
    "Twinfalls Peaks",
    "Brightwater Heights",
    "Hollowstream Peaks",
    "Rivermist Waters",
    "Stonespring Heights",
    "Windstream Peaks",
    "Silverfalls Heights",
    "Hawkriver Peaks",
    "Eagleriver Heights"
];

const farmlandAdjacentToMountainsProvinceNames = [
    "Mountainfield",
    "Stonevale Farms",
    "Highridge Meadows",
    "Ironhill Farms",
    "Greenpeak Valley",
    "Stonebrook Farms",
    "Mountainshade",
    "Rockfield Farms",
    "Eaglecrest Fields",
    "Thornhill Farms",
    "Mountainside Meadows",
    "Stonemere Farms",
    "Hillshade Farms",
    "Rockvale Fields",
    "Silvercrest Farms",
    "Cliffside Meadows",
    "Stoneridge Farms",
    "Highpeak Fields",
    "Ironvale Farms",
    "Hillcrest Meadows",
    "Stonefield Farms",
    "Greenridge Farms",
    "Rockshade Fields",
    "Mountainview Meadows",
    "Thornfield Farms",
    "Eldermount Fields",
    "Hilltop Farms",
    "Rockhill Meadows",
    "Stonecrest Farms",
    "Greenshade Fields",
    "Ironpeak Farms",
    "Hawksridge Fields",
    "Thornvale Meadows",
    "Cliffside Farms",
    "Stonehaven Fields",
    "Greenfield Farms",
    "Mountainside Fields",
    "Silverhill Farms",
    "Stonemount Meadows",
    "Hillview Farms",
    "Rockfield Meadows",
    "Thorncrest Farms",
    "Mountainbrook Fields",
    "Stonevale Fields",
    "Greenside Farms",
    "Ironhill Fields",
    "Hillshade Meadows",
    "Rockridge Farms",
    "Greenhill Fields",
    "Stoneridge Meadows",
    "Highcrest Farms",
    "Stonebrook Fields",
    "Hawkshade Farms",
    "Cliffside Fields",
    "Greenpeak Farms",
    "Ironcrest Meadows",
    "Hillvale Farms",
    "Stonemere Fields",
    "Rockvale Meadows",
    "Silverbrook Farms",
    "Stonefield Meadows",
    "Highpeak Farms",
    "Hillcrest Fields",
    "Greenridge Meadows",
    "Mountainfield Farms",
    "Rockshade Meadows",
    "Thornfield Fields",
    "Stoneridge Farms",
    "Greenshade Meadows",
    "Ironvale Fields",
    "Hawksridge Farms",
    "Stonecrest Meadows",
    "Hilltop Fields",
    "Mountainview Farms",
    "Silvercrest Meadows",
    "Cliffside Fields",
    "Hillview Meadows",
    "Stonevale Meadows",
    "Greenhill Farms",
    "Ironpeak Meadows",
    "Thornvale Fields",
    "Stonehaven Meadows",
    "Highridge Farms",
    "Hillshade Fields",
    "Rockfield Farms",
    "Thornhill Meadows",
    "Greenfield Meadows",
    "Mountainshade Farms",
    "Eldermount Meadows",
    "Silverhill Fields",
    "Stonemount Farms",
    "Hillvale Meadows",
    "Stonebrook Farms",
    "Greenside Fields",
    "Ironhill Meadows",
    "Mountainbrook Farms",
    "Rockridge Fields"
];

const coastalProvinceWithSignificantRiversProvinceNames = [
    "Riverhaven",
    "Tidewater",
    "Brineridge",
    "Wavecrest",
    "Rivermouth",
    "Seaford",
    "Stormriver",
    "Harborbrook",
    "Riverside",
    "Oceanflow",
    "Baywater",
    "Riverrun",
    "Brinefall",
    "Seabrook",
    "Waveglen",
    "Tiderush",
    "Stormwater",
    "Seaspray",
    "Riversurge",
    "Oceanrise",
    "Bayriver",
    "Rivergale",
    "Brinewave",
    "Seaflow",
    "Wavebay",
    "Tidecrest",
    "Stormstream",
    "Harborrush",
    "Riverbend",
    "Oceanward",
    "Baysurge",
    "Rivershade",
    "Brinebrook",
    "Seamouth",
    "Waveridge",
    "Tidesurge",
    "Stormcurrent",
    "Seastrand",
    "Riverbay",
    "Oceanview",
    "Bayglen",
    "Rivercross",
    "Brineglen",
    "Seaswell",
    "Waveford",
    "Tideway",
    "Stormbrook",
    "Harborwave",
    "Rivermere",
    "Oceanside",
    "Baystream",
    "Riverwave",
    "Brinerun",
    "Seafall",
    "Wavehaven",
    "Tidebrook",
    "Stormwave",
    "Seaglen",
    "Riversong",
    "Oceanspray",
    "Baycurrent",
    "Riverway",
    "Brinesurge",
    "Seaford",
    "Wavefall",
    "Tidestream",
    "Stormriver",
    "Harborcrest",
    "Riverward",
    "Oceanswell",
    "Baycrest",
    "Riverflow",
    "Brineridge",
    "Seasong",
    "Waverun",
    "Tideflow",
    "Stormbay",
    "Seawatch",
    "Riverswell",
    "Oceancrest",
    "Baywave",
    "Riversworn",
    "Brineview",
    "Seaforge",
    "Wavecrest",
    "Tiderun",
    "Stormshore",
    "Harbormere",
    "Riverview",
    "Oceanstream",
    "Baystrand",
    "Riverfall",
    "Brinewatch",
    "Seabright",
    "Wavemere",
    "Tideview",
    "Stormglen",
    "Seawind",
    "Riverbright",
    "Oceanbrook",
    "Bayrun"
];

const largeMountainRangeProvinceNames = [
    "Stonepeak Range",
    "Thundercliff Mountains",
    "Ironspire Range",
    "Frostcrag Peaks",
    "Shadowridge Mountains",
    "Stormfrost Range",
    "Eaglecrest Mountains",
    "Dragonspire Range",
    "Grimrock Mountains",
    "Silverpeak Range",
    "Wolfbane Mountains",
    "Ironclad Peaks",
    "Highspire Range",
    "Stormpeak Mountains",
    "Eldercrest Range",
    "Fireforge Mountains",
    "Frostfire Range",
    "Brimstone Peaks",
    "Darkridge Mountains",
    "Thundershield Range",
    "Stormvale Mountains",
    "Ravencrag Peaks",
    "Steelspire Range",
    "Shadowpeak Mountains",
    "Windrider Range",
    "Stoneforge Mountains",
    "Thornspire Range",
    "Dragoncrest Peaks",
    "Snowshield Range",
    "Grimspire Mountains",
    "Ironridge Peaks",
    "Eaglepeak Range",
    "Blizzardclaw Mountains",
    "Thundershadow Range",
    "Silvercliff Peaks",
    "Wyrmspire Mountains",
    "Darkforge Range",
    "Frostshadow Mountains",
    "Windcrest Peaks",
    "Stormcrag Range",
    "Highcliff Mountains",
    "Thornridge Peaks",
    "Steelcrag Range",
    "Ravenshadow Mountains",
    "Frostvale Range",
    "Eldershadow Mountains",
    "Dragonclaw Peaks",
    "Stormridge Range",
    "Ironshadow Mountains",
    "Grimvale Range",
    "Silverforge Mountains",
    "Thunderspine Range",
    "Windspire Peaks",
    "Frostpeak Mountains",
    "Darkvale Range",
    "Thornclaw Mountains",
    "Stoneclad Peaks",
    "Highshadow Range",
    "Blizzardspire Mountains",
    "Thornshield Range",
    "Ironcrag Peaks",
    "Stormspire Range",
    "Grimclad Mountains",
    "Silvervale Range",
    "Wyrmshadow Mountains",
    "Eagleshadow Range",
    "Windshadow Mountains",
    "Dragonridge Range",
    "Steelcliff Peaks",
    "Thundershadow Mountains",
    "Frostclad Range",
    "Highspire Peaks",
    "Darkcrag Mountains",
    "Elderpeak Range",
    "Blizzardridge Mountains",
    "Stormclad Range",
    "Ravenpeak Mountains",
    "Ironcrest Range",
    "Grimshadow Peaks",
    "Thornpeak Mountains",
    "Snowspire Range",
    "Stoneforge Peaks",
    "Windrider Mountains",
    "Steelvale Range",
    "Dragonshadow Peaks",
    "Highcrag Mountains",
    "Thunderspine Peaks",
    "Elderridge Range",
    "Stormcliff Mountains",
    "Ironpeak Range",
    "Grimrider Mountains",
    "Silverclad Peaks",
    "Darkshield Range",
    "Thorncliff Mountains",
    "Blizzardvale Range",
    "Stormridge Peaks",
    "Ravenclaw Mountains",
    "Ironspire Range",
    "Windclad Mountains",
    "Stonevale Range",
    "Silverpeak Peaks",
    "Thundershield Mountains"
];

const centralDesertProvinceNames = [
    "Sandhaven",
    "Sunfire Dunes",
    "Blightreach",
    "Dunecrest",
    "Desolation Vale",
    "Dustwhisper",
    "Scorchwind",
    "Sandspine",
    "Aridholm",
    "Sunstorm",
    "Desert's Heart",
    "Dunewatch",
    "Ashenwaste",
    "Sandspire",
    "Blazewind",
    "Suncrest",
    "Shadowsands",
    "Heatwave",
    "Sunset Dunes",
    "Dryfall",
    "Sandshadow",
    "Searingsands",
    "Dunescar",
    "Sundown",
    "Ashenreach",
    "Burningwaste",
    "Sandrift",
    "Dunefield",
    "Scorched Valley",
    "Sunstrike",
    "Dustpeak",
    "Sandveil",
    "Blazehaven",
    "Sunblight",
    "Aridsands",
    "Dunelight",
    "Desert's Edge",
    "Heatspire",
    "Sunchaser",
    "Dryglen",
    "Sandcliff",
    "Scorchfall",
    "Sunstorm Dunes",
    "Duskdunes",
    "Sandstorm",
    "Blightwind",
    "Dunefire",
    "Desert's Hold",
    "Sandbreeze",
    "Dustburn",
    "Searingspire",
    "Ashencrest",
    "Blazeward",
    "Sunshadow Dunes",
    "Drywaste",
    "Duneheart",
    "Sandfall",
    "Scorchedspine",
    "Sunburnt",
    "Aridcrest",
    "Suncall",
    "Dustfield",
    "Sandwave",
    "Heatstorm",
    "Desert's Reach",
    "Sunchaser Dunes",
    "Duneflame",
    "Blazecliff",
    "Sandglen",
    "Ashencliff",
    "Searingspire Dunes",
    "Blightsands",
    "Sunspire",
    "Drywatch",
    "Duneshadow",
    "Scorched Ridge",
    "Sunstorm Valley",
    "Dustspire",
    "Sandridge",
    "Blazepeak",
    "Heatcrest",
    "Sundown Dunes",
    "Aridshadow",
    "Sunfire Valley",
    "Scorchveil",
    "Sandstrike",
    "Ashenspire",
    "Duststorm",
    "Searing Ridge",
    "Blightcrest",
    "Dunecliff",
    "Suncall Valley",
    "Heatfall",
    "Sundown Ridge",
    "Scorchedcliff",
    "Searingsands Dunes",
    "Ashenveil",
    "Dustblight",
    "Sunburnt Valley"
];

const isolatedFarmlandsProvinceNames = [
    "Farmer's Hope",
    "Green Hollow",
    "Meadow's End",
    "Quiet Haven",
    "Solace Fields",
    "Humble Hearth",
    "Whispering Wheat",
    "Lonely Croft",
    "Old Orchard",
    "Peaceful Pasture",
    "Seclusion Farm",
    "Harvest Home",
    "Silent Hill",
    "Crescent Fields",
    "Autumn's Rest",
    "Gentle Grove",
    "Sunset Farm",
    "Hidden Vale",
    "Tranquil Acres",
    "Willow's End",
    "Fallow Fields",
    "Brightmoor",
    "Windswept Farm",
    "Cedar Hollow",
    "Golden Harvest",
    "Stillwater Farm",
    "Lonesome Lane",
    "Whispering Pines",
    "Elderberry Fields",
    "Quiet Corner",
    "Heatherview",
    "Old Mill Farm",
    "Windsong Acres",
    "Silent Meadows",
    "Greenhaven",
    "Shady Nook",
    "Briarwood Farm",
    "Sunshine Valley",
    "Orchard's Edge",
    "Timber's Rest",
    "Solitude Springs",
    "Golden Grove",
    "Fernhill Farm",
    "Shadowbrook",
    "Brightfield",
    "Maplewood Farm",
    "Dewdrop Downs",
    "Peaceful Glen",
    "Honeysuckle Farm",
    "Rustic Meadows",
    "Amber Fields",
    "Sunnybank",
    "Mossy Glen",
    "Shady Acres",
    "Dawnlight Farm",
    "Rosewood Fields",
    "Willowbrook",
    "Heron's Nest",
    "Quail's Run",
    "Cloverfield",
    "Eagle's Rest",
    "Autumnvale",
    "Brookside Farm",
    "Hearthwood",
    "Primrose Acres",
    "Elderwood",
    "Gentlebrook",
    "Brackenridge",
    "Starfall Fields",
    "Highland Farm",
    "Oakshade",
    "Whispering Glen",
    "Larkspur Fields",
    "Springfield",
    "Candlewood",
    "Lakeside Farm",
    "Fernbrook",
    "Shadewood",
    "Rosewood Glen",
    "Birchwood Farm",
    "Misty Hollow",
    "Cypress Grove",
    "Summerfield",
    "Thornhill Farm",
    "Wildflower Meadows",
    "Briar Glen",
    "Glendale Farm",
    "Silverbrook",
    "Hilltop Haven",
    "Crimson Fields",
    "Morningdew Farm",
    "Brambleshire",
    "Brighton Farm",
    "Cedarbrook",
    "Dewdrop Farm",
    "Honeysuckle Glen",
    "Willowfield",
    "Hazelwood Farm",
    "Riverside Farm",
    "Lakeside Fields"
];

const tundraNoRiversProvinceNames = [
    "Frostfell",
    "Iceridge",
    "Snowveil",
    "Glacier Hollow",
    "Winter's Rest",
    "Coldreach",
    "Frozen Moor",
    "Frostbite Fields",
    "Bitterwind",
    "Icebound Heath",
    "Snowdrift",
    "Frostglen",
    "Winterbloom",
    "Chillgrove",
    "Northwatch",
    "Frozen Vale",
    "Frostpine",
    "Snowpeak",
    "Iceclaw",
    "Whitewood",
    "Snowy Hollow",
    "Frostmeadow",
    "Frostshade",
    "Icestone",
    "Snowfall",
    "Wintershade",
    "Coldspire",
    "Frozen Ridge",
    "Frostwild",
    "Bitterfield",
    "Snowy Ridge",
    "Icehaven",
    "Frostbrook",
    "Wintersong",
    "Chillwood",
    "Glacier Point",
    "Frozenwood",
    "Frostgate",
    "Icelands",
    "Snowy Plains",
    "Frostvale",
    "Wintersreach",
    "Frostford",
    "Coldwood",
    "Snowy Vale",
    "Icevale",
    "Winterhaven",
    "Frostguard",
    "Snowfield",
    "Frozenwood",
    "Icewild",
    "Wintersend",
    "Coldstone",
    "Frostwood",
    "Snowy Hollow",
    "Iceshade",
    "Winterstone",
    "Frostholm",
    "Frozenbluff",
    "Chillspire",
    "Glaciervale",
    "Winterglen",
    "Frostbloom",
    "Snowy Bluff",
    "Icepine",
    "Winterwood",
    "Frostfield",
    "Frozenhearth",
    "Chillvale",
    "Snowvale",
    "Frostcliff",
    "Iceglen",
    "Winterhold",
    "Snowy Moor",
    "Frostmoor",
    "Iceland",
    "Frozenwood",
    "Snowspire",
    "Frostcrest",
    "Snowy Peak",
    "Icecrest",
    "Wintersedge",
    "Frozenvale",
    "Frostlake",
    "Winterfrost",
    "Snowfield",
    "Coldpoint",
    "Iceholm",
    "Frosthaven",
    "Snowshade",
    "Winterglade",
    "Frostland",
    "Snowlands",
    "Icepeak",
    "Frosthill",
    "Frozenpeak",
    "Snowcliff",
    "Winterlands",
    "Icelake",
    "Chillhaven",
    "Frostreach"
];

const fertileCoastalProvinceNames = [
    "Riverside Meadows",
    "Brightwater Fields",
    "Seagrass Plains",
    "Harvest Shores",
    "Riverbend",
    "Goldentide",
    "Verdant Cove",
    "Sunlit Shores",
    "Tidal Fields",
    "Seaflower Plains",
    "Greenwater",
    "Meadowbrook",
    "Harvest Bay",
    "Lushhaven",
    "Silverfields",
    "Sunset Cove",
    "Tide's Reach",
    "Fertile Bay",
    "Springtide",
    "Seaward Meadows",
    "Greenglen",
    "Bayharvest",
    "Verdant Shore",
    "Rivershore",
    "Sunvale",
    "Harvestlight",
    "Brightbay",
    "Tidewater Fields",
    "Seagrove",
    "Greenfields",
    "Rivermeadow",
    "Goldengrove",
    "Meadowshore",
    "Sunlit Bay",
    "Lushfields",
    "Seaside Plains",
    "Verdant Bay",
    "Springwater",
    "Riversong",
    "Greenshore",
    "Baymeadows",
    "Tidewood",
    "Harvest Cove",
    "Brightmeadow",
    "Seaward Fields",
    "Greenhaven",
    "Sunset Fields",
    "Lushcove",
    "Golden Bay",
    "Riverfields",
    "Meadowbay",
    "Springtide Shores",
    "Seaflower Meadows",
    "Verdant Cove",
    "Tidefields",
    "Sunlit Meadows",
    "Greenshores",
    "Bayharvest Fields",
    "Riverhaven",
    "Goldenshore",
    "Sunvale Fields",
    "Seaward Cove",
    "Brightwater Plains",
    "Lushbay",
    "Tidal Cove",
    "Meadowgrove",
    "Harvest Bay Fields",
    "Greenmeadow",
    "Silver Bay",
    "Tidefield Shores",
    "Springmeadow",
    "Riverside Bay",
    "Golden Plains",
    "Seagrass Fields",
    "Verdant Fields",
    "Baymeadow",
    "Sunlit Fields",
    "Harvest Shores Fields",
    "Brightshore",
    "Seaward Bay",
    "Greenbay",
    "Rivertide",
    "Lushgrove",
    "Tide Meadows",
    "Meadowtide",
    "Springbay",
    "Seaflower Bay",
    "Verdant Grove",
    "Goldenfield",
    "Sunset Meadows",
    "Green Shores",
    "Bayharvest Shores",
    "Riverfield Shores",
    "Meadowlight",
    "Harvestcove",
    "Tidewood Fields",
    "Silvermeadow",
    "Brightbay Shores"
];

const dryCoastalProvinceNames = [
    "Sunblaze Shores",
    "Dunewatch",
    "Arid Coast",
    "Sandwhisper Bay",
    "Scorched Haven",
    "Parched Cove",
    "Blazewater",
    "Dustmere",
    "Desolate Beach",
    "Sunscorch Bay",
    "Windswept Dunes",
    "Drywater",
    "Saltblaze",
    "Seaworn Dunes",
    "Desert's Edge",
    "Scorching Tide",
    "Sunbaked Bay",
    "Burnt Sands",
    "Dusty Shores",
    "Searidge",
    "Heatwave Coast",
    "Ashen Bay",
    "Desertwave",
    "Sunset Dunes",
    "Arid Shores",
    "Sandridge Bay",
    "Scorched Tide",
    "Parched Sands",
    "Blaze Bay",
    "Dusty Beach",
    "Drywave",
    "Seablaze",
    "Sunburn Coast",
    "Sear Shores",
    "Desolate Dunes",
    "Scorching Coast",
    "Sunblaze Bay",
    "Burnt Coast",
    "Dustwhisper Shores",
    "Heatblaze",
    "Ashen Shore",
    "Desertwave Bay",
    "Sunset Sands",
    "Aridwave",
    "Sandburn Coast",
    "Scorchedwater",
    "Parched Ridge",
    "Blazewave",
    "Dusty Bay",
    "Dryblaze",
    "Seaworn Sands",
    "Sunburn Dunes",
    "Searwave",
    "Desolate Shore",
    "Scorching Beach",
    "Sunblaze Ridge",
    "Burnt Dunes",
    "Dustwhisper Bay",
    "Heatwave Shores",
    "Ashen Coast",
    "Desertblaze",
    "Sunset Shore",
    "Aridburn",
    "Sandwave Coast",
    "Scorched Ridge",
    "Parchedwater",
    "Blazeshore",
    "Dusty Ridge",
    "Dryshore",
    "Seablaze Ridge",
    "Sunburn Sands",
    "Sear Ridge",
    "Desolate Ridge",
    "Scorching Sands",
    "Sunblaze Shore",
    "Burnt Ridge",
    "Dustwhisper Coast",
    "Heatwave Beach",
    "Ashen Sands",
    "Desertshore",
    "Sunset Ridge",
    "Aridshore",
    "Sandburn Ridge",
    "Scorchedblaze",
    "Parched Shores",
    "Blazeworn",
    "Dustyburn",
    "Drywave Ridge",
    "Seablaze Shore",
    "Sunburn Ridge",
    "Searblaze",
    "Desolate Coast",
    "Scorching Ridge",
    "Sunblaze Beach",
    "Burnt Shore",
    "Dustwhisper Ridge",
    "Heatwave Ridge",
    "Ashen Ridge",
    "Desertburn"
];

const wetlandWithMultipleRiversProvinceNames = [
    "Riverfen",
    "Mistmarsh",
    "Twinbrook",
    "Watershadow",
    "Rivermoor",
    "Frostrill",
    "Marshglade",
    "Rivendel",
    "Waveswamp",
    "Mirebrook",
    "Glacierfen",
    "Waterglade",
    "Swamphaven",
    "Riverwisp",
    "Silvermarsh",
    "Everfen",
    "Mossmire",
    "Riverveil",
    "Tidewater",
    "Marshwater",
    "Frostmire",
    "Mirevale",
    "Rivermist",
    "Brackenfen",
    "Wetlandia",
    "Greenwater",
    "Shadowfen",
    "Willowmire",
    "Brookmarsh",
    "Marshspring",
    "Fenbrook",
    "Rivershade",
    "Watervale",
    "Frostfen",
    "Mossybrook",
    "Riverrun",
    "Windmarsh",
    "Shimmerfen",
    "Mirewater",
    "Brackenmire",
    "Greenfen",
    "Wavespring",
    "Marshwood",
    "Twinriver",
    "Riverfall",
    "Waterspring",
    "Swampwood",
    "Willowfen",
    "Silverfen",
    "Evermarsh",
    "Mistwood",
    "Riverhollow",
    "Frostrun",
    "Marshmeadow",
    "Rivenglade",
    "Shadyfen",
    "Watershadow",
    "Shadowmire",
    "Windfen",
    "Brookfen",
    "Glaciermarsh",
    "Greenmire",
    "Mossyfen",
    "Shimmerwater",
    "Rivershadow",
    "Willowmarsh",
    "Frostglade",
    "Mirewood",
    "Brackenwater",
    "Everwater",
    "Marshveil",
    "Riverwood",
    "Twinfen",
    "Waterrun",
    "Mistfen",
    "Windwater",
    "Shadowmire",
    "Greenmarsh",
    "Brookmire",
    "Marshbrook",
    "Silverwater",
    "Riverspring",
    "Watershadow",
    "Willowrun",
    "Frostmire",
    "Brackenwood",
    "Evermire",
    "Marshglade",
    "Rivengrove",
    "Waveshadow",
    "Shadywater",
    "Windmire",
    "Riversong",
    "Twinmire",
    "Greenmire",
    "Mistwater",
    "Willowbrook",
    "Shadybrook",
    "Watersong"
];

const highlandDesertProvinceNames = [
    "Sunspire Heights",
    "Desert's Edge",
    "Arid Summit",
    "Scorching Heights",
    "Dunewatch",
    "Blazewind Peaks",
    "Highridge Desert",
    "Stormcrag",
    "Golden Dunes",
    "Sunblaze Ridge",
    "Windscorch",
    "Sands of Altara",
    "Drywind Peaks",
    "Thundershade",
    "Hightide Dunes",
    "Blightstone",
    "Suncrest Cliffs",
    "Dustpeak",
    "Scorched Heights",
    "Dunefall",
    "Windblaze",
    "Sunstorm Heights",
    "Aridcliff",
    "Stoneblaze",
    "Thunderbluff",
    "Sunchaser",
    "High Desert",
    "Dustspire",
    "Blazefury Ridge",
    "Goldenbluff",
    "Scorchvale",
    "Sunscorched",
    "Thundersand",
    "Dunefury",
    "Windcrag",
    "Blightcliff",
    "Sunburnt Peaks",
    "Stormpeak",
    "Goldencliff",
    "Dustshade",
    "Blazeward",
    "Sunset Dunes",
    "Aridwind",
    "Stonefire",
    "Thunder Heights",
    "Sunflare",
    "Scorchfall",
    "Windpeak",
    "Blightward",
    "Sunshadow",
    "Dustblaze",
    "Dunecrest",
    "Stormshade",
    "Highdune",
    "Goldenward",
    "Thunderspire",
    "Sunspire",
    "Scorching Cliffs",
    "Windflare",
    "Blightpeak",
    "Sunstone",
    "Dustward",
    "Blazestone",
    "Sunset Ridge",
    "Aridpeak",
    "Stoneburn",
    "Thundercrag",
    "Sunshadow Peaks",
    "Scorchwind",
    "Windburn",
    "Dunebluff",
    "Stormward",
    "Goldenpeak",
    "Dustfire",
    "Blazeguard",
    "Sunrise Cliffs",
    "Highwind",
    "Blightsummit",
    "Sunchaser Ridge",
    "Scorched Crags",
    "Windward",
    "Dunestone",
    "Stormblaze",
    "Goldenshadow",
    "Thundercliff",
    "Sunflare Ridge",
    "Scorchspine",
    "Dustburn",
    "Blazemoor",
    "Sunstrike",
    "Aridguard",
    "Stonestorm",
    "Thunderstone",
    "Suncrest Ridge",
    "Scorching Ridge",
    "Windguard",
    "Dunestrike",
    "Blightfire"
];

const lowlandSwampProvinceNames = [
    "Mirewood",
    "Bogshire",
    "Frostdell",
    "Marshwood",
    "Brackenfen",
    "Willowswamp",
    "Thornmarsh",
    "Eldermire",
    "Shadowfen",
    "Greenglen",
    "Fogmoor",
    "Whispering Bog",
    "Frostbog",
    "Ravenmarsh",
    "Mossglen",
    "Darkwood Swamp",
    "Gloomire",
    "Mistwood Fen",
    "Bogreach",
    "Shademire",
    "Mireglen",
    "Briarfen",
    "Elderbog",
    "Thornswamp",
    "Greenfen",
    "Frostmire",
    "Willowfen",
    "Ravenmire",
    "Brackenmarsh",
    "Mossfen",
    "Shadewood Swamp",
    "Greymire",
    "Frostdale",
    "Shadowbog",
    "Whispering Fen",
    "Eldermarsh",
    "Fogfen",
    "Ravenglen",
    "Mosswood",
    "Darkfen",
    "Gloommire",
    "Mirewood Swamp",
    "Bogshadow",
    "Thornfen",
    "Greenmire",
    "Frostfen",
    "Willowmire",
    "Shadowmarsh",
    "Brackenbog",
    "Elderswamp",
    "Shadewood Fen",
    "Greenswamp",
    "Mistfen",
    "Briarmire",
    "Ravenbog",
    "Fogmire",
    "Mossmarsh",
    "Darkmarsh",
    "Gloomwood",
    "Marshglen",
    "Bogmire",
    "Thornmire",
    "Greenwood Swamp",
    "Frostwood Fen",
    "Willowswamp Fen",
    "Shadowglen",
    "Elderglen",
    "Brackenswamp",
    "Mistmire",
    "Briarwood Swamp",
    "Ravenfen",
    "Fogmarsh",
    "Mossbog",
    "Darkglen",
    "Gloomswamp",
    "Mirefen",
    "Bogwood",
    "Thornwood Fen",
    "Greenbog",
    "Frostdale Fen",
    "Willowglen",
    "Shadewood Mire",
    "Greymarsh",
    "Eldermoss",
    "Brackenwood Swamp",
    "Mistbog",
    "Briarbog",
    "Ravenswamp",
    "Fogsfen",
    "Mossglen Swamp",
    "Darkfen Swamp",
    "Gloomfen",
    "Miremarsh",
    "Bogreach Swamp",
    "Thornfen Swamp",
    "Greenmoss",
    "Frostshadow",
    "Willowmarsh Fen"
];

const alpineMeadowProvinceNames = [
    "Highmeadow",
    "Sunset Fields",
    "Brightvale",
    "Whispering Heights",
    "Verdant Ridge",
    "Eagle's Meadow",
    "Goldencrest",
    "Lushfield",
    "Windridge",
    "Sunblossom",
    "Mountain Bloom",
    "Greenshire",
    "Frostfield",
    "Hilltop Grove",
    "Silverbloom",
    "Meadowglen",
    "Springvale",
    "Verdant Heights",
    "Highflower",
    "Thistle Ridge",
    "Brighthollow",
    "Meadowspire",
    "Sunchaser",
    "Highvale",
    "Greensummit",
    "Briarcrest",
    "Meadowpeak",
    "Goldenglen",
    "Frostmeadow",
    "Hillshade",
    "Sunnyridge",
    "Meadowshade",
    "Greencrest",
    "Blossom Ridge",
    "Hilltop Haven",
    "Lushspire",
    "Sunridge",
    "Meadowmist",
    "Silvercrest",
    "Highgrove",
    "Springfield",
    "Verdant Blossom",
    "Whispering Glen",
    "Brightspire",
    "Hilltop Vale",
    "Sundew Ridge",
    "Meadowvale",
    "Goldenfield",
    "Thistlewood",
    "Meadowbrook",
    "Frostvale",
    "Hillflower",
    "Suncrest",
    "Greenmeadow",
    "Hilltop Meadow",
    "Silversummit",
    "Meadowridge",
    "Brightbloom",
    "Sunchaser Fields",
    "Highridge",
    "Whispering Fields",
    "Verdant Meadow",
    "Lushpeak",
    "Goldenshire",
    "Meadowvale Heights",
    "Thistlehaven",
    "Springbloom",
    "Greenshadow",
    "Hilltop Bloom",
    "Meadowhill",
    "Brightcrest",
    "Sunnybloom",
    "Frostflower",
    "Hillspire",
    "Sunblossom Fields",
    "Greenridge",
    "Meadowhaven",
    "Silvermeadow",
    "Spring Ridge",
    "Lushmeadow",
    "Thistlebloom",
    "Highhill",
    "Verdantvale",
    "Hilltop Ridge",
    "Sunvale",
    "Brightflower",
    "Meadowpeak Heights",
    "Whispering Meadow",
    "Goldenpeak",
    "Frostridge",
    "Greenbloom",
    "Hilltop Field",
    "Silverglen",
    "Lushfield Heights",
    "Sunblossom Meadow",
    "Thistleridge",
    "Meadowridge Fields",
    "Verdant Crest",
    "Hillcrest",
    "Meadowtop"
];

const tropicalRainForestProvinceNames = [
    "Emerald Wilds",
    "Jade Canopy",
    "Verdant Thicket",
    "Lushwood",
    "Greenheart",
    "Sunshadow Jungle",
    "Rainshade",
    "Tanglewood",
    "Verdant Grove",
    "Whispering Rainforest",
    "Rainfall Glen",
    "Mistwood",
    "Elderjungle",
    "Frostrun Rainforest",
    "Greentide",
    "Shadowgrove",
    "Brightleaf Jungle",
    "Wilds of Eldara",
    "Sunshadow Rainforest",
    "Greenbloom",
    "Rainforest of Yore",
    "Thornwood",
    "Emerald Canopy",
    "Tanglewood Forest",
    "Greenmist Jungle",
    "Sunmist Rainforest",
    "Rainwood",
    "Whispering Grove",
    "Greenthorn",
    "Verdant Vale",
    "Jungle of Ages",
    "Eldergreen",
    "Lushglade",
    "Greenglen",
    "Shademist",
    "Sunwhisper Jungle",
    "Brightleaf Rainforest",
    "Mossvale",
    "Rainshadow",
    "Wildgrove",
    "Greenwild",
    "Frostwood Jungle",
    "Eldershade",
    "Thornshade",
    "Emerald Grove",
    "Verdantwood",
    "Tanglevale",
    "Greenfall",
    "Sunbreeze Jungle",
    "Rainforest Glade",
    "Whispering Jungle",
    "Mistrun",
    "Greenthicket",
    "Eldermist",
    "Lushshade",
    "Shadowrun Rainforest",
    "Sunshadow Grove",
    "Greenmist Rainforest",
    "Rainbloom",
    "Verdant Bloom",
    "Brightwood Jungle",
    "Jade Grove",
    "Sunwhisper Rainforest",
    "Elderglen",
    "Wildwood",
    "Frostrun Jungle",
    "Greenshade",
    "Rainfall Forest",
    "Mistgrove",
    "Whispering Vale",
    "Tanglewild",
    "Greenwhisper",
    "Eldergrove",
    "Sunshadow Vale",
    "Jungle of Shadows",
    "Lushbloom",
    "Brightshade Jungle",
    "Rainforest Glen",
    "Sunmist Jungle",
    "Greenleaf",
    "Wildshade",
    "Rainwood Vale",
    "Verdant Grove Rainforest",
    "Eldershade Jungle",
    "Tangleshadow",
    "Greenvale",
    "Sunbreeze Rainforest",
    "Rainshadow Forest",
    "Whispering Run",
    "Thornwild",
    "Emeraldwood",
    "Verdantshadow",
    "Brightgrove",
    "Lushgrove Jungle",
    "Mossvale Rainforest",
    "Rainforest of Elders",
    "Sunwhisper Grove",
    "Greenthorn Jungle",
    "Elderbloom"
];

const temperateHighlandForestProvinceNames = [
    "Highwood",
    "Frostleaf",
    "Glenwood Heights",
    "Shadowglen",
    "Eldercrest",
    "Verdant Highlands",
    "Whispering Pines",
    "Oakenshade",
    "Mistywood",
    "Greenridge",
    "Eagle's Glen",
    "Brightwood",
    "Sunshadow Forest",
    "Frostvale",
    "Highforest",
    "Ravencrest",
    "Thornwood",
    "Silverglen",
    "Hawkridge",
    "Evergreen Heights",
    "Briarglen",
    "Stormwood",
    "Ashenvale",
    "Windcrest",
    "Highpine",
    "Shadewood",
    "Eldergrove",
    "Brackenridge",
    "Highcliff Forest",
    "Greenwood",
    "Hollowsong",
    "Frostwood",
    "Briarcrest",
    "Highspire",
    "Glenhaven",
    "Evercrest",
    "Mistyridge",
    "Wolf's Glen",
    "Starlight Woods",
    "Highgrove",
    "Elderwood",
    "Stormvale",
    "Verdant Ridge",
    "Shadowvale",
    "Suncrest",
    "Thornridge",
    "Ashenwood",
    "Brightvale",
    "Windwood",
    "Hawkwood",
    "Silverleaf",
    "Frostspire",
    "Highridge",
    "Ravenwood",
    "Briargrove",
    "Greenhaven",
    "Eagleshadow",
    "Stormglen",
    "Evervale",
    "Mistridge",
    "Elderwood Heights",
    "Wolfcrest",
    "Whispering Glen",
    "Sunshadow Heights",
    "Greenvale",
    "Hawkridge Forest",
    "Frostglen",
    "Thornvale",
    "Ashenridge",
    "Highleaf",
    "Brackenwood",
    "Shadowglen Heights",
    "Evergreen Forest",
    "Brightleaf",
    "Windridge",
    "Silvercrest",
    "Stormridge",
    "Hollowvale",
    "Elderhaven",
    "Greenridge Forest",
    "Mistyvale",
    "Sunwood",
    "Thorncrest",
    "Whispering Ridge",
    "Hawkcrest",
    "Brightwood Heights",
    "Frostrain",
    "Shadowwood",
    "Highhaven",
    "Eagle's Ridge",
    "Briarwood",
    "Stormcrest",
    "Everwood",
    "Ravenwood Heights",
    "Ashencrest",
    "Windglen",
    "Silverwood",
    "Hollowcrest",
    "Greenleaf",
    "Mistwood Heights"
];

const coastalSteppeProvinceNames = [
    "Seawind Heath",
    "Brinefield Shores",
    "Wavecrest Fields",
    "Saltmarsh Meadows",
    "Tidewater Downs",
    "Stormshore Meadows",
    "Brineheath",
    "Seabreeze Downs",
    "Windward Fields",
    "Coastline Meadows",
    "Saltmeadow",
    "Oceanside Downs",
    "Tidebound Heath",
    "Wavewash Downs",
    "Seaward Heath",
    "Brinecoast Meadows",
    "Stormbreeze Downs",
    "Seaspray Meadows",
    "Windwhisper Downs",
    "Coastal Heath",
    "Saltwind Meadows",
    "Tidecall Downs",
    "Oceanheath",
    "Brineshore Meadows",
    "Seamist Downs",
    "Wavecrash Meadows",
    "Windtide Downs",
    "Saltcrest Meadows",
    "Stormcall Downs",
    "Seafront Meadows",
    "Brinewave Downs",
    "Coastwatch Meadows",
    "Seagale Downs",
    "Windward Downs",
    "Tidewhisper Meadows",
    "Saltshore Meadows",
    "Oceanspray Downs",
    "Brinestone Meadows",
    "Seawind Downs",
    "Wavecrest Downs",
    "Windbluff Downs",
    "Coastline Heath",
    "Tidewater Meadows",
    "Saltbluff Downs",
    "Seamarch Meadows",
    "Brineflow Downs",
    "Seasong Meadows",
    "Windcall Downs",
    "Stormshore Downs",
    "Seaborn Meadows",
    "Tidecrest Heath",
    "Saltbreeze Meadows",
    "Wavecrest Heath",
    "Oceanwhisper Meadows",
    "Seafury Downs",
    "Brinevale",
    "Stormwind Heath",
    "Seafront Downs",
    "Windshore Downs",
    "Seamere",
    "Tidewave Downs",
    "Brinewhisper",
    "Saltwave Meadows",
    "Oceanshadow",
    "Seamist Downs",
    "Brinecove",
    "Wavebreaker Heath",
    "Saltwind Downs",
    "Seawhisper",
    "Tidefall Meadows",
    "Stormbluff Downs",
    "Brinebluff",
    "Windcrest Downs",
    "Saltmarch",
    "Seawood",
    "Wavecall Downs",
    "Stormcall Heath",
    "Tideway Meadows",
    "Saltshadow",
    "Brineward",
    "Seamere Downs",
    "Windshore Heath",
    "Tiderun Meadows",
    "Stormtide Downs",
    "Saltbrine",
    "Wavecrest",
    "Oceancrest Downs",
    "Tidecall Heath",
    "Brinewatch",
    "Seabluff",
    "Saltwood",
    "Wavehaven",
    "Oceanscall",
    "Windward Downs",
    "Brinewave",
    "Stormwave Heath",
    "Seafront",
    "Saltreach",
    "Brineflow",
    "Windshore",
    "Tidewood"
];

const dryInlandSteppeProvinceNames = [
    "Dustheath",
    "Aridreach",
    "Windspire",
    "Sunfall",
    "Barrenwood",
    "Thornfield",
    "Dustwhisper",
    "Drymarsh",
    "Sandrift",
    "Thistledown",
    "Scorchvale",
    "Highdust",
    "Sunshade",
    "Drywind",
    "Stonebluff",
    "Windvale",
    "Dustgrove",
    "Parched Plains",
    "Thornridge",
    "Heatmoor",
    "Dustvale",
    "Windward",
    "Sunblaze",
    "Aridvale",
    "Dryhaven",
    "Rockshade",
    "Thornmere",
    "Scorchtide",
    "Highplain",
    "Dustshadow",
    "Windcrest",
    "Sundown",
    "Drycliff",
    "Stonefield",
    "Windwhisper",
    "Heatshade",
    "Dustfall",
    "Rockvale",
    "Suncrest",
    "Thornhill",
    "Parched Vale",
    "Dustpeak",
    "Aridshade",
    "Windheath",
    "Dryvale",
    "Sunstorm",
    "Rockburn",
    "Duststorm",
    "Heatridge",
    "Windridge",
    "Thornspire",
    "Dryrun",
    "Sunspire",
    "Aridstone",
    "Dustcliff",
    "Parchedridge",
    "Windfall",
    "Rockshadow",
    "Dryreach",
    "Sunchaser",
    "Highheath",
    "Thornfield",
    "Heatcrest",
    "Dustwood",
    "Windswept",
    "Sunbluff",
    "Aridwood",
    "Drygrove",
    "Rockvale",
    "Thornshade",
    "Dustfire",
    "Highvale",
    "Windshadow",
    "Heatbluff",
    "Dryshadow",
    "Sundown",
    "Aridgrove",
    "Windmoor",
    "Dustrock",
    "Parchedwood",
    "Suncliff",
    "Thornridge",
    "Rockfall",
    "Dryburn",
    "Heatshadow",
    "Highspire",
    "Windspire",
    "Dustbluff",
    "Sunchase",
    "Aridspire",
    "Parchedfield",
    "Sunfall",
    "Thornfall",
    "Rockgrove",
    "Dustshade",
    "Highbluff",
    "Windshade",
    "Heatfield",
    "Dryspire",
    "Rockspire"
];

const lushValleyProvinceNames = [
    "Greenhaven",
    "Rivervale",
    "Meadowbrook",
    "Verdant Hollow",
    "Riverglen",
    "Greenshire",
    "Elmwood Valley",
    "Brightfield",
    "Willowbrook",
    "Sunvale",
    "Evergreen Valley",
    "Briarfield",
    "Golden Valley",
    "Lushmeadow",
    "Rivershire",
    "Greenglen",
    "Springfield",
    "Willowglen",
    "Sunshadow Valley",
    "Mosswood",
    "Greenthorn",
    "Silverbrook",
    "Elmshade",
    "Verdant Grove",
    "Riverwood",
    "Highmeadow",
    "Lushfield",
    "Springvale",
    "Meadowgrove",
    "Willowspring",
    "Greenwood",
    "Briarglen",
    "Goldengrove",
    "Sunshadow Vale",
    "Evergreen Hollow",
    "Brightmeadow",
    "Riversong",
    "Greenthistle",
    "Elmridge",
    "Verdant Meadows",
    "Riverstone",
    "Highfield",
    "Willowvale",
    "Suncrest",
    "Mossvale",
    "Greengrove",
    "Silvermeadow",
    "Elmvale",
    "Verdantfield",
    "Riverbend",
    "Meadowvale",
    "Lushgrove",
    "Springglen",
    "Willowridge",
    "Sunhaven",
    "Greenvalley",
    "Briarwood",
    "Goldenshire",
    "Sunbright",
    "Evergreen Vale",
    "Brightvale",
    "Riverspring",
    "Greencrest",
    "Elmspring",
    "Verdantwood",
    "Rivercross",
    "Highglen",
    "Lushhaven",
    "Springmeadow",
    "Meadowfield",
    "Willowfield",
    "Greenspring",
    "Briarvale",
    "Goldenfield",
    "Sunbrook",
    "Evergreen Grove",
    "Brightglen",
    "Riverview",
    "Greengrove Valley",
    "Elmshadow",
    "Verdantbrook",
    "Riverglen Vale",
    "Highvale",
    "Lushbrook",
    "Springwood",
    "Meadowridge",
    "Willowbend",
    "Greentide",
    "Briarshade",
    "Goldenbrook",
    "Sunridge",
    "Everfield",
    "Brightwood",
    "Rivershade",
    "Greenhill",
    "Elmgrove",
    "Verdantcrest",
    "Rivercrest",
    "Highgrove",
    "Lushfield Valley",
    "Springhaven"
];

