let frenchSeed = `
La chapelle Sixtine (en italien, Cappella Sistina), appelée originellement chapelle de Sixte, est une des salles des palais pontificaux du Vatican et fait partie des Musées du Vatican. Remplaçant la chapelle Pauline, puis le palais du Quirinal, la chapelle Sixtine est le lieu où, traditionnellement depuis le XVe siècle, les cardinaux réunis en conclave élisent le nouveau pape, et obligatoirement depuis la constitution apostolique édictée par Jean-Paul II en 1996, intitulée Universi Dominici gregis1.

Dédiée à l'Assomption de Marie, elle est la chapelle principale du palais apostolique, ainsi que l'un des trésors culturels et artistiques les plus célèbres de la Cité du Vatican. Elle a été construite entre 1475 et 1481 environ, à l'époque du pape Sixte IV della Rovere, dont elle tire son nom.

Des cérémonies officielles papales (dont dans le passé aussi quelques couronnements papaux) s'y déroulent. Elle est décorée d'œuvres d'art parmi les plus connues et célébrées de l'art occidental, dont les célèbres fresques de Michel-Ange, qui couvrent la voûte (1508-1512)2 et le mur du fond (Jugement dernier) au-dessus de l'autel (vers 1535-1541). Les murs sont décorés d'une série de fresques de certains des plus grands artistes italiens de la seconde moitié du XVe siècle (Sandro Botticelli, Pietro Perugino, Pinturicchio, Domenico Ghirlandaio, Luca Signorelli, Piero di Cosimo, Cosimo Rosselli et autres). Elle est ainsi considérée comme peut-être la plus complète et la plus importante de cette théologie visuelle, qui a été appelée « Biblia pauperum »3.

Il y a aussi une « Chapelle Sixtine » dans la basilique Sainte-Marie-Majeure à Rome, construite par Sixte V, et une dans la cathédrale de Savone, construite par Sixte IV comme mausolée pour ses parents.

Chaque jour, quelque 10 000 touristes la visitent, avec des pointes de 20 000 personnes aux périodes d'affluence. Cette concentration humaine provoque de multiples exhalaisons de gaz carbonique et risque, à terme, d'endommager les peintures4.
Histoire
XVe siècle
Sandro Botticelli, Sixte II.

L'existence d'une chapelle papale est mentionnée dès 1368, la « Capella magna » (la Cappella Maggiore en italien), destinée à accueillir les célébrations liturgiques ou cérémonielles de la cour pontificaleN 1 et à partir de 1492, les conclaves. Elle est décorée, entre autres, par Giottino, Giovanni da Milano et Fra Angelico5.
Reconstruction

Pendant la Papauté d'Avignon, la ville de Rome subit de très graves troubles civils ; plusieurs monuments chrétiens délaissés tombent en ruine. La « Capella magna » est délabrée, si bien qu'après le retour des papes à Rome en 1455, les conclaves doivent se tenir dans la chapelle Paolina6. Dès lors, l'un des projets les plus ambitieux des papes du XVe siècle, à commencer par Martin V, est de restaurer les monuments chrétiens les plus importants de Rome, dévastés par l'abandon, la négligence et les troubles civils7. Sixte IV, ancien professeur de théologie dans les grandes universités italiennes et général des franciscains, reprend cet engagement et, peu de temps après son élection (août 1471), entame un travail de récupération et de monumentalisation du tissu urbain de Rome qui culmine dans la reconstruction et la décoration de la chapelle palatine du Palais apostolique, qui prend plus tard son nom. Les travaux de rénovation de la chapelle sont commandés par le pape lors de son jubilé de 1475.

Précédée d'une antichambre - la Sala Regia -, la chapelle se situe à l'angle sud-ouest du palais. Elle comprend un souterrain, un entresol et la chapelle proprement dite. Elle est ceinte, en hauteur, d'un chemin de garde défensif.

Le projet architectural prend forme dès 1473. Il est confié à deux architectes, les noms de Baccio Pontelli et de Giovannino de' Dolci ont été suggérés par des historiens sans toutefois en apporter la preuve6. Ils auraient reproduit les dimensions du Temple de Salomon, soit 40,92 mètres de long sur 13,41 mètres de large et 20,69 mètres de haut8 (on observe que 21 : 13 = 1,61, ce qui correspond au nombre d'or souvent utilisé par les architectes de jadis).

Les travaux débutent en 1477 et sont achevés vers la fin 1480. En 1477, les restes en ruine du bâtiment précédent sont démolis pour permettre d'exploiter les fondations et constituer la base des murs sains de la nouvelle chapelle. Le sol est recouvert de marbres polychromes. Un jubé grillagée en marbre, œuvre de Mino da Fiesole sépare l'espace réservé aux clercs de celui accessible aux laïcs. Il semble que les murs médiévaux aient été conservés jusqu'à la hauteur de la première charpente, justifiant les irrégularités du plan7 : les plus grands côtés convergent vers celui du bas, qui à son tour n'est pas parfaitement parallèle à celui de l'autel9. De nouvelles voûtes sont construites à la fois dans le toit et dans les salles des maîtres de cérémonie sous la chapelle9. La chapelle est fortifiée contre de nombreux ennemis potentiels, tels la République de Florence ou les Turcs de Mehmed II10. Sa structure, recouverte d'une couche de briques, est couronnée d'une voûte en berceau maçonnée remplaçant la précédente construction en bois. Un jubé — ou plus précisément une transenne — divise la chapelle en deux parties. Le sol comprend deux niveaux, dont un étage supérieur percé de douze hautes fenêtres cintrées11. Les conclaves s'y déroulent de nouveau à partir du XVIe siècle, les cardinaux siégeant sur des banquettes en pierre qui longent les trois côtés6.

Les fonctions de la chapelle n'ont pas changé par rapport à celles précédentes et à celles analogues dans le Palais des Papes à Avignon, comme le siège des cérémonies les plus solennelles de l'année liturgique auxquelles assistent la cour papale. Cette nécessité exige un cadre particulièrement somptueux, qui montre sans équivoque les Maiestas papalis aux participants admis à y assister, qui sont essentiellement le collège des cardinaux, les généraux des ordres monastiques, les diplomates accrédités, les membres du plus haut rang de l'État papal, le sénateur et les conservateurs de la ville de Rome, les patriarches, évêques et princes ou personnalités éminentes en visite. À ceux-ci s'ajoutent tous ceux, nombreux, admis à assister aux célébrations au-delà de la transenne en marbre qui sépare encore l'actuelle chapelle papale de l'autel7.

À l'été 1481, la construction devait être achevée car la décoration des fresques des murs est déjà documentée7. L'apparence de l'extérieur doit être grandiose, comparable uniquement aux bâtiments de l'époque impériale.

La chapelle est consacrée lors de la première messe de la fête de l'Assomption du 15 août 1483 à l'Assomption de la Vierge Marie.
Décoration picturale

Le programme général de la décoration picturale de la chapelle est réparti sur trois registres de bas en haut: le socle avec de fausses tapisseries, le second ordre avec des scènes de l'Ancien Testament (scènes de la vie de Moïse) et du Nouveau Testament (scènes de la vie du Christ) et enfin le plus haut ordre avec la représentation des papes martyrs.

La décoration picturale commence sur le mur derrière l'autel (celui aujourd'hui avec le Jugement dernier ) où Pérugin, qui a déjà travaillé pour le pape dans la Cappella della Concezione de l'ancienne basilique vaticane, réalise un retable représentant l'Assomption de la Vierge. La voûte est décorée d'un ciel bleu constellé où de petites boules de cire dorée, collées sur la peinture, figurant les étoiles par le maestro dell'Annuciazione Gardner12, suivant la tradition médiévale. Un tel décor, plus simple à réaliser que des fresques à personnages, est fréquent dans les chapelles contemporaines. Toutefois, les examens effectués lors des dernières restaurations n’ont mis au jour aucune trace de bleu13.

Les fresques sont réalisées, entre 1481 et 1482, par les meilleurs peintres florentins, ombriens et toscans de l'époque : le seigneur de Florence Laurent de Médicis, dans le cadre d'une politique de réconciliation avec les opposants qui ont soutenu la Conjuration des Pazzi (1478), dont le pape lui-même, propose d'envoyer les meilleurs artistes présents sur la scène florentine de l'époque, en tant qu'ambassadeurs de la beauté, de l'harmonie et de la primauté culturelle de Florence. L'offre est acceptée et le 27 octobre 1480, Sandro Botticelli, Cosimo Rosselli, Domenico Ghirlandaio et leurs collaborateurs respectifs partent pour Rome, où ils sont documentés au travail à partir du le printemps 148114.

Chacun de ces artistes, avec l'aide de ses collaborateurs Pinturicchio, Piero di Cosimo et Bartolomeo della Gatta, peint l'un des quatre panneaux sur le mur à droite de l'autel, puis, avec un nouveau contrat daté du 27 octobre 1481, ils sont reconfirmés pour l'exécution des dix autres panneaux restants (les deux sur le mur de l'autel avaient déjà été achevés par le Pérugin dans la toute première phase) à terminer en mars de l'année suivante. Les termes ne sont pas toujours respectés ; Luca Signorelli succède au Pérugin, qui a peint à la fresque le Testament et la mort de Moïse et la Contention autour du corps de Moïse sur le mur de l'entrée12. Le programme iconographique complexe est défini dans les moindres détails par le pape lui-même et ses conseillers, même si cette complexité même nécessite une intervention importante des artistes dans l'invention figurative et iconographique15. À noter la petite contribution picturale du maître Filippo Brunelleschi dans l'aile nord du bâtiment. Selon certains historiens, la conception du programme iconographique global a été reprise de l'Expositio super septem visiones libri apocalypsis, une exégèse d'épisodes bibliques remontant peut-être au IXe siècle16, ou de l'œuvre de Joachim de Fiore, auteur d'une théorie complexe de la « concorde » entre l'Ancien et le Nouveau Testament.

Le cycle présente une grande homogénéité, malgré la participation d'artistes aux personnalités nettement différentes. Cela a été possible grâce à l'adoption de la même échelle dimensionnelle des figures et de la structuration rythmique aux mêmes nuances dominantes, parmi lesquelles se distingue l'abondance des finitions dorées, qui intensifient la lumière avec des effets qui devaient paraître particulièrement suggestifs à la lueur des torches et des bougies17.

Les emblèmes héraldiques de Sixte IV, peints et sculptés, représentant des feuilles de chêne et des glands, symbolisant son patronyme Della Rovere (du chêne en italien)11 parsèment le décor6.

    Reconstitution de l'intérieur de la chapelle Sixtine avant l'intervention de Michel-Ange.
    Reconstitution de l'intérieur de la chapelle Sixtine avant l'intervention de Michel-Ange.
    Messe solennelle coram papa à la chapelle Sixtine avec Sixte IV. Miniature de Giuliano Amidei, musée Condé.
    Messe solennelle coram papa à la chapelle Sixtine avec Sixte IV. Miniature de Giuliano Amidei, musée Condé.

XVIe siècle
Un des murs de la chapelle.

Le splendide complexe voulu par Sixte IV demeure dans les décennies suivantes au centre des intérêts des papes, avec des interventions qui constituent des pages fondamentales de l'art de la Haute Renaissance17.
Jules II

Au printemps 1504, la nature particulière du terrain sur lequel se dresse la chapelle provoque probablement une inclinaison du mur sud qui, à la suite d'affaissements, laisse une fissure importante et menaçante dans le plafond, ce qui nécessite une suspension de toutes les fonctions ecclésiastiques dans la chapelle par précaution18. Jules II della Rovere fait consolider la voûte par des chaînes, à la fois au-dessus de la voûte principale et dans les salles inférieures, rendant la chapelle à nouveau accessible après la mi-octobre. La longue fissure, découverte à partir du coin nord-est, est bouchée par l'insertion de nouvelles briques, peut-être à l'été 150418. Le décor de la voûte du maestro dell'Annuciazione Gardner est irrémédiablement endommagé.

Le Plafond de la Chapelle, où se trouve la voûte, décorée de fresques achevées par Michel-Ange en quatre ans, est inaugurée par Jules II le 31 octobre 1512. Pape guerrier, assoiffé de pouvoir et désireux de rendre à Rome sa splendeur passée, il avait déjà fait appel à Michel-Ange pour la conception de son immense tombeau, projet qui restera inachevé19. L'idée de faire refaire la décoration de la voûte par Michel-Ange doit lui venir en avril 1506, comme en témoigne une lettre envoyée à l'artiste par le maître d'œuvre florentin Piero Rosselli, qui a appris la nouvelle du pape lui-même. Le départ précipité de Michel-Ange de Rome, en raison des intrigues qui ont bloqué son projet grandiose pour le tombeau, suspend le projet jusqu'à la réconciliation avec le pape qui a lieu en 1507.

En 1508, l'artiste retourne à Rome et signe le contrat17. La décoration de la voûte rencontre de nombreuses difficultés, toutes brillamment surmontées par l'artiste et ses collaborateurs. Pour pouvoir atteindre le plafond, Michel-Ange a besoin d'une structure de support ; la première idée est de Bramante, qui veut lui construire un échafaudage spécial, suspendu dans les airs au moyen de cordes. Mais Michel-Ange craint que cette solution laisse des trous dans le plafond une fois les travaux terminés ; il construit donc lui-même un échafaudage, une simple plate-forme en bois sur des supports faits de trous dans les murs placés en haut près des fenêtres. Cet échafaudage est déplacé par étapes afin de permettre un travail facile dans chaque partie de la voûte. La première couche de plâtre étalée commence à moisir car elle est trop humide. Michel-Ange doit l'enlever et recommencer en essayant un nouveau mélange créé par l'un de ses assistants, Jacopo Torni, qui non seulement résiste à la moisissure, mais entre désormais dans la tradition de la construction italienne.

Initialement, Michel-Ange est chargé de ne peindre que douze personnages, les apôtres, mais lorsque le travail est terminé, il y en a plus de trois cents présents. De nombreux dessins subsistent de l'entreprise, documents très précieux.
Léon X
Guérison de l'infirme, l'un des cartons de Raphaël pour les tapisseries de la Sixtine, V&AM, Londres.

Léon X souhaite également associer son nom au prestige inégalé de la Chapelle Sixtine, jusqu'alors parrainée par les papes de la famille Della Rovere. Il décide alors de faire don d'une série de précieuses tapisseries tissées à Bruxelles sur un dessin de Raphaël à la fin de 1514. Les tapisseries, tissées dans l'atelier de Pieter van Aelst, montrent les Histoires des saints Pierre et Paul, dont les sujets ont des correspondances précises avec les panneaux peints à la fresque du registre central17. Couvrant la zone destinée au pape et aux religieux séparés par la transenne de marbre, elles étaient utilisées lors des cérémonies solennelles et pouvaient être lues, comme les histoires au-dessus, depuis le mur de l'autel20.

A travers la célébration des deux premiers « architectes de l'Église », les apôtres Pierre et Paul, œuvrant respectivement envers les Juifs et envers les « Gentils », le lien avec le souverain pontife, leur héritier20, est réaffirmé.

Lorsque les sept premières tapisseries arrivent de Flandre et sont installées, le 26 décembre 1519, le maître de cérémonie Paris de Grassis note : « tota cappella stupefacta est in aspectu illorum »20.
De nouveaux dégâts

Dans les années suivantes, de nouveaux affaissements de terrain causent, en raison de la mauvaise stabilité des fondations, de nouveaux dommages, tels que l'effondrement, le jour de Noël 1522, de l'architrave du portail, qui tue un garde suisse à proximité d'Adrian VI qui, à ce moment, entre dans la chapelle20.

Lors du conclave de 1523, de nouvelles fissures inquiétantes apparaissent, ce qui nécessite une intervention urgente d'Antonio da Sangallo qui, appelé par les cardinaux concernés, vérifie la stabilité du bâtiment. Plus tard, de nouvelles interventions sont nécessaires sur les fondations du mur oriental, qui endommagent irrémédiablement les deux fresques qui clôturaient les Histoires du Christ et de Moïse. Plus tard, dans la seconde moitié du XVIe siècle, les deux scènes sont repeintes par Hendrick van de Broeck et Matteo Pérez, certainement les interventions picturales les plus faibles de tout le décor20.
Clément VII et Paul III
Michel-Ange, Daniel.

Enfin, la dernière grande décoration de la chapelle est initiée par Clément VII, qui commande, à nouveau à Michel-Ange, la fresque immense du Jugement dernier (1536-1541), en grande partie peinte à l'époque de Paul III Farnèse, qui est également la première intervention « destructrice » dans l'histoire de la chapelle, modifiant le cadre spatial et iconographique d'origine qui avait été conçu dans les contributions précédentes, jusqu'alors substantiellement coordonnées17.

La première mention de l'intention du pontife figure dans une lettre de Sebastiano del Piombo à Michel-Ange, datée du 17 juillet 1533, qui l'invite à retourner à Rome. Les résistances initiales de l'artiste sont vaincues en 1533 et en 1534, il quitte définitivement Florence, également en raison de son aversion envers le nouveau duc Alexandre de Médicis, ainsi que de sa désaffection croissante envers les œuvres florentines pour lesquelles il éprouve de plus en plus de lassitude21.

Le Jugement dernier fait l'objet d'une violente dispute entre le cardinal Carafa et Michel-Ange : l'artiste est accusé d'immoralité et d'obscénités intolérables car il a peint des figures nues, avec les parties génitales en évidence, à l'intérieur de l'église la plus importante du christianisme, et doit donc subir la censure. Une campagne (connue sous le nom de « campagne des feuilles de figuier ») est organisée par Carafa et monseigneur Sernini (ambassadeur de Mantoue) pour retirer les fresques. Giorgio Vasari raconte que lorsque le maître de cérémonie du pape, Biagio da Cesena, met en question son travail en le qualifiant de plus approprié pour un bain thermal que pour une chapelle, Michel-Ange représente ses traits dans la figure de Minos, juge des enfers ; quand Biagio da Cesena s'en plaint au pape, le pontife répond que sa juridiction ne s'applique pas à l'enfer, et ainsi le portrait est resté. Selon d'autres savants22, cependant, le personnage représenté sous des formes caricaturales dans le Minos serait Pierre-Louis Farnèse, fils du pape Paul III, connu à Rome pour être un sodomite violent et pour avoir abusé sexuellement d'un jeune ecclésiastique, causant sa mort.

Coïncidant avec la mort de Michel-Ange, une loi est promulguée pour couvrir les organes génitaux (« Pictura in Cappella Ap.ca coopriantur »). Ainsi Daniele da Volterra, un apprenti de Michel-Ange, peint toute une série de draperies et de pagnes appelés « braghe », ce qui lui a valu le surnom de « Braghettone ».
Siècles suivants

Lorsque le Mahatma Gandhi visite la Chapelle Sixtine en 1931, son attention est frappée, plus que par les fresques de Michel-Ange, par le crucifix sur l'autel. Il s'attarde pendant plusieurs minutes devant ce crucifix - qui représente un Jésus très maigre, humble et souffrant, très différent du Jésus corpulent et fort du Jugement dernier -, s'exclamant finalement : « On ne peut s'empêcher d'être ému aux larmes »23.

Les fresques que Michel-Ange a réalisées dans la chapelle Sixtine, et en particulier celles de la voûte et des lunettes qui l'accompagnent, ont subi de nombreuses restaurations au cours des siècles, dont la plus récente a eu lieu entre 1980 et 1994. Ces dernières ont étonné les savants et les amateurs d'art24 car elles ont mis en lumière des couleurs et des détails que la patine sombre cachait depuis des siècles. Le choix à faire pour le retrait ou non des « braghe » de Daniele da Volterra a été particulièrement controversé. Il a été décidé de supprimer la plupart des pagnes sauf ceux des personnages principaux, qui sont maintenant entrés dans l'imaginaire collectif, comme celui de la figure de Daniel ; une copie fidèle et non censurée de l'original, par Marcello Venusti, se trouve aujourd'hui à Naples au Musée de Capodimonte.
Description
Vue de la chapelle depuis les jardins du Vatican.

La chapelle est située à droite de la basilique Saint-Pierre, à l'intérieur du palais apostolique, accessible depuis l'imposante Sala Regia.
Architecture

La chapelle a un plan de basilique et mesure 40,93 mètres de long sur 13,41 de large (les dimensions du temple de Salomon, comme indiqué dans l'Ancien Testament). Elle a une hauteur de 20,70 mètres et est couverte par une voûte en berceau abaissée, reliée aux murs par des voiles et des pendentifs, qui génèrent des lunettes en correspondance avec les parois latérales. Sous chaque lunette, s'ouvrent les étroites fenêtres cintrées qui éclairent l'environnement : il y en a six sur chaque paroi latérale auxquelles ont été ajoutées deux autres ouvertures côté ouest, condamnées lors de la création du Jugement dernier7.

La corniche entre les zones inférieure et moyenne dépasse légèrement de la suivante, entre les zones centrale et supérieure ; à cet endroit, à hauteur des volets des fenêtres, le mur s'éloigne pour laisser place à une allée étroite. Au-delà, les piliers, qui dans toute la partie inférieure ne sont que peints, deviennent réels et soutiennent les corbeaux de la voûte9.

Au-dessus du portail, suivant la pente de la voûte, est représenté le grand blason papal des Della Rovere avec le chêne, douze glands d'or et le diadème papal, appartenant à Sixte IV, mais réalisé à l'époque de Jules II, son neveu25.
Plancher

Le sol du XVe siècle est composé d'incrustations de marbre polychrome dans le style Cosmatesque. Les dessins marquent le chemin processionnel qui va de l'entrée à la porte avec une série de cercles connectés, flanqués sur les côtés de carrés remplis de différents motifs. Dans l'espace le plus intérieur, devant l'autel, les mosaïques au sol indiquent la disposition du trône papal et des sièges des cardinaux, ainsi que le mouvement des célébrants pendant les cérémonies7.
Transenne et chœur
Ingres, Cantoria de la chapelle Sixtine, 1848.

Une transenne de marbre de Mino da Fiesole, Andrea Bregno et Giovanni Dalmata divise la chapelle en deux parties ; la plus grande, avec l'autel, est réservée aux cérémonies religieuses et autres usages cléricaux, tandis que la plus petite est réservée aux fidèles. L'iconostase était à l'origine en fer plaqué d'or et dans une position plus centrale : elle a ensuite été déplacée vers la partie destinée aux fidèles pour donner plus d'espace au pape et à sa cour. Le socle est composé de panneaux finement sculptés en bas-relief dorés, avec des angelots tenant des guirlandes aux armoiries de Sixte IV alternant avec des motifs végétaux ornementaux, surmontés de piliers qui entrecroisent les portes et soutiennent l'architrave, au-delà desquelles des candélabres en marbre sont disposés20.

La cantoria est également des mêmes artistes, espace d'environ cinq mètres de large et deux mètres de profondeur sur le mur de droite, réservé au chœur : c'est le pape Sixte IV qui crée, peu après son élection (9 août 1471), un Collège des aumôniers Cantori, premier noyau du futur chœur de la chapelle Sixtine. Au-delà de la riche balustrade décorée et dorée, étaient accueillis les chanteurs, généralement douze, qui accompagnaient les cérémonies liturgiques21 .

La transenne divisait à l'origine la chapelle presque en deux, plus ou moins à la hauteur de La Création d'Ève, comme cela est visible au niveau du sol. La nécessité d'avoir un espace plus grand dans le chœur a conduit à un déplacement d'environ cinq mètres vers sa position actuelle dans les années 188026.
Fresques
Ghirlandaio, La Vocation des premiers apôtres Pierre et Paul.
Pérugin, La Remise des clés à saint Pierre.
Botticcelli, La Punition des rebelles.

Le décor pictural a été conçu en relation étroite avec les proportions architecturales de la chapelle et en suivant l'ordonnancement des murs. Les cloisons sont basées sur l'implantation des fenêtres, ce qui génère de la place pour six panneaux sous chaque fenêtre des parois latérales et pour deux sur les parois avant et arrière12.

Verticalement, les fresques sont réalisées sur trois registres : un inférieur avec de faux rideaux, pour lequel les tapisseries de Raphaël ont ensuite été exécutées ; un intermédiaire avec les Histoires de Moïse et Aaron sur le côté gauche et les Histoires de Jésus sur le côté droit, avec des correspondances importantes entre un mur et l'autre ; un supérieur, au-delà d'une corniche fortement saillante, qui coïncide avec le niveau des fenêtres et qui à son tour peut être divisé en deux sous-registres, l'un avec les figures des premiers papes (de Pierre à Marcel Ier) dans des niches sur les côtés de la fenêtres, et l'autre, au-delà d'une autre corniche en saillie, avec des lunettes peintes plus tard par Michel-Ange. Le mur du bas présente un schéma similaire, avec au centre, en correspondance avec l'autel, un retable décorée de fresques par Le Pérugin avec l'Assomption, qui était dédiée à la chapelle et vénérée par Sixte IV12.

Les correspondances entre les paires de panneaux symétriques entre un mur et l'autre - basées sur l'iconographie typologique - sont rendues explicites par les inscriptions (tituli) dans la frise au-dessus, l'ancien préfigure le nouveau et le nouveau est perfectionné par l'ancien, selon un concept déjà exprimé par saint Augustin : « Dieu, l'inspirateur et l'auteur des livres de l'un et l'autre Testaments, a sagement disposé que le nouveau était caché dans l'ancien et que l'ancien devenait clair dans le nouveau ».
Les différentes sections des murs de la chapelle : le rideau de fausses tentures peintes aux couleurs héraldiques de la famille de Sixte IV, les fresques représentant des épisodes de la vie de Moïse et du Christ, la galerie des papes et les lunettes représentant les ancêtres du Christ.

Le message sous-jacent est donc comment Moïse, premier guide et législateur du peuple élu, avec l'aide du prêtre Aaron, a préfiguré le Christ, sous la bannière de la continuité de la loi divine qui, dans le renouvellement du Décalogue dans la nouvelle alliance du Nouveau Testament, est ensuite transmise par Jésus à saint Pierre et à ses successeurs, c'est-à-dire aux pontifes eux-mêmes12. En ce sens, la scène de La Remise des clefs à saint Pierre confiée au Pérugin, qui témoigne du passage de ces pouvoirs, joue un rôle fondamental ; de l'autre côté, La Punition des rebelles, par Botticelli, fait plutôt allusion au châtiment qui incombe à quiconque s'oppose à l'autorité du pontife15. Il s'agit donc d'une réaffirmation solennelle de nature politique et doctrinale de la primauté de saint Pierre, de son caractère sacré, de son intangibilité et de la plénitude des pouvoirs du pontife.

Le cycle de la Sixtine représente une gigantesque histoire spirituelle de l'humanité : de la création au péché, au salut, à la fin du monde. Les fresques sur les murs sont une représentation du royaume de la loi et de celui de la grâce, rendu dans un ton commémoratif et hagiographique. Michel-Ange a compris la création et le péché comme des tragédies pour l'ensemble de l'humanité, et la Rédemption comme un acte d'espoir et de foi qui se produit à chaque instant et en tout lieu. La doctrine néoplatonicienne, présente dans sa formation culturelle, le conduit à une profonde spiritualité intérieure. Les différentes figures ont, outre une signification littérale (Histoires du peuple élu), une fonction plus universelle de révélation des humeurs de l'homme après le péché : la tristesse de l'attente inconsciente (Ancêtres du Christ), l'espérance aveugle d'affronter le miracle (Salut d'Israël), sérénité virile de la conscience du futur (Prophètes et Sibylles)27.
Murs latéraux
Isaïe, par Michel-Ange.

L'intérêt de la chapelle réside non seulement dans les célèbres fresques de sa voûte, dues à Michel-Ange, mais aussi dans les peintures moins connues de ses murs, œuvres d'artistes aussi éminents que Botticelli, Le Pérugin, le Pinturicchio ou Domenico Ghirlandaio. Ces scènes ont, semble-t-il, été commandées par Sixte IV ou par un théologien de la cour pontificale, dans le but politique précis de démontrer la primauté de la papauté et son indépendance face aux monarques de la chrétienté. Ces murs sont divisés horizontalement en trois bandes séparées par des entablements, et verticalement par des lésènes. Le long de la bande inférieure se déploie une rangée de damas peints en trompe-l’œil, ornés de feuilles de chêne et de glands (armes parlantes expliquées ci-dessus). Dans la bande médiane sont placées, face à face, des scènes de la vie de Moïse (sur la paroi sud, à gauche lorsqu'on fait face à l'autel) et du Christ (sur la paroi nord, à droite face à l'autel) ; des inscriptions (tituli) expliquent ces correspondances. Le cycle se finit sur la paroi de l'entrée de la chapelle. La bande supérieure montre les portraits des trente-deux premiers papes, insérés dans des niches monochromes6. Au-dessus des fenêtres de chacune des parois, les lunettes sont peintes par Michel-Ange et représentent les ancêtres du Christ. Ils sont au nombre de 40 comme David, Salomon ou encore Achim. Mais ces ancêtres n’ont pas tous été identifiés car les plaques sont trop endommagées. L’humanité est, par ces ancêtres, représentée comme une famille.

Les scènes de la vie de Moïse et du Christ représentent :

    Le Voyage de Moïse en Égypte par Le Pérugin (mur sud) ;
    Le Baptême du Christ par Le Pérugin (mur nord) ;
    Épisodes de la vie de Moïse (Le Meurtre du soldat égyptien, La Protection des filles de Jéthro, Le Buisson ardent) par Botticelli (mur sud) ;
    La Tentation du Christ au désert par Botticelli (mur nord) ;
    Le Passage de la mer Rouge par Cosimo Rosselli (mur sud) ;
    La Vocation des premiers apôtres Pierre et André par Ghirlandaio (mur nord) ;
    La Remise des Tables de la Loi par Cosimo Rosselli (mur sud) ;
    Le Sermon sur la montagne par Cosimo Rosselli (mur nord) ;
    Le Châtiment de Coré, Datan et Abiram, qui ont tenté de lapider Moïse par Botticelli (mur sud) ;
    La Remise des clefs à saint Pierre et La Tentative de lapider Jésus par Le Pérugin (mur nord) ;
    Moïse remet son commandement à Josué par Luca Signorelli (mur sud) ;
    La Cène par Cosimo Rosselli (mur nord) ;
    mur d'entrée : La Dispute autour du corps de Moïse (par Matteo de Lecce, pour remplacer une fresque endommagée de Luca Signorelli) qui finit le cycle de Moïse que l'on retrouve paroi sud ; et La Résurrection (par Hendrick van den Broeck dit Arrigo Fiammingo, pour remplacer une fresque endommagée de Domenico Ghirlandaio) qui finit le cycle du Christ que l'on retrouve paroi nord.

Les artistes se sont amusés à glisser de nombreux clins d'œil dans leurs peintures, et notamment à y cacher des portraits de leurs contemporains28.
Voûte
La voûte.
Article détaillé : Plafond de la chapelle Sixtine.

La décoration du plafond de la chapelle Sixtine fut commandée par le pape Jules II, au début de son pontificat (1503-1513), pour remédier aux désordres causés par les constructions de la basilique Saint-Pierre et de la tour Borgia, qui avaient fragilisé la chapelle. En 1504, une longue fissure provoqua des dégâts si importants que le pape chargea Michel-Ange de refaire la décoration de l'édifice8. En mai 1508, l'artiste signa le contrat prévoyant la représentation des douze apôtres sur les pendentifs, agrémentée de motifs ornementaux dans les parties restantes. Mais Michel-Ange jugea ce sujet trop pauvre. Sur sa requête, et grâce à l'aide des théologiens de la cour papale, il conçut neuf scènes centrales inspirées du néoplatonisme, représentant des épisodes de la Genèse.

La série commence par La Séparation de la lumière d'avec les ténèbres et se poursuit avec la célèbre Création d'Adam où Dieu tend la main vers le premier Homme pour lui insuffler la vie, puis la Tentation et d'autres épisodes. Ces panneaux sont encadrés de sculpturaux athlètes nus (les célèbres Ignudi), qui soutiennent des médaillons en camaïeu d'or illustrant des scènes tirées du Livre des Rois. Critiquée dès l'origine, la présence des Ignudi reste, aujourd'hui encore, sujette à discussion : faut-il y voir des éléments païens, sans rapport aucun avec le caractère sacré de la composition ou, au contraire, des anges dépourvus d'ailes, mais faisant partie intégrante du programme iconographique ? À la base de la structure architectonique, douze voyants dont sept prophètes et cinq sibylles siègent sur des trônes monumentaux, au-dessus d'ancêtres du Christ logés sur les voussures ou dans les lunettes situées dans les parois nord et sud, et sur le mur d'entrée. Enfin, sur les pendentifs des quatre angles, l'artiste a peint des épisodes du salut miraculeux du peuple d'Israël.

Michel-Ange dessina de nombreuses études et cartons préparatoires et conçut des dizaines de personnages aux poses variées. Un travail aussi démesuré ne pouvait qu'affecter sa santé (cf. l'article détaillé et le témoignage de Michel-Ange lui-même). Toutefois, l'image d'un Michel-Ange peignant couché semble tenir de la légende. Une esquisse de Michel-Ange dans la marge d'un sonnet adressé à Giovanni di Benedetto da Pistoia le représente d'ailleurs debout la tête inclinée vers l'arrière et le bras tendu vers le haut.

Ces représentations impressionnantes, qui démontrent une parfaite maîtrise du mouvement des corps et de l'anatomie humaine, ont radicalement transformé la peinture occidentale. En août 1510, Michel-Ange avait terminé la première moitié de la voûte, du mur d'entrée jusqu'à la Création d’Ève. Les travaux étaient probablement achevés avant le 31 octobre 1512, où Jules II présida les vêpres solennelles de la Toussaint avant de célébrer la messe dès le lendemain4.

Dans son roman historique Le ciel de la chapelle Sixtine29, Leon Morell décrit dans le détail, avec vraisemblance, la réalisation de la fresque.
Le Jugement dernier
Article détaillé : Le Jugement dernier (Michel-Ange).
Le Jugement dernier (détail).
Le Christ et la Vierge.

Le Jugement dernier est une fresque peinte par Michel-Ange, alors âgé de 60 ans, sur le mur de l'autel de la chapelle Sixtine. Commandé par le pape Clément VII, le travail dura six ans et fut inauguré par son successeur Paul III le 1er novembre 1541.

En 1532, Michel-Ange revient à Rome après un séjour de plusieurs années à Florence, où il a pris parti contre Clément VII dans le conflit qui l'opposait à l'empereur Charles Quint. Le pape, qui a pardonné, lui demande de remplacer les peintures des deux extrémités de la chapelle Sixtine par deux grandioses représentations : La Chute des anges rebelles et Le Jugement dernier. Presque aussitôt, le peintre entame les études nécessaires à ce projet démesuré. En septembre 1534], Clément VII meurt et Michel-Ange espère pouvoir renoncer à cette tâche écrasante pour se remettre au tombeau de Jules II, qu'il regrette de n'avoir pu achever. Mais le nouveau pape Paul III entend que le projet de son prédécesseur soit mené à terme. Par bref apostolique de 1535, il nomme Michel-Ange architecte, peintre et sculpteur du Vatican. Michel-Ange ne peut se dérober. Toutefois seul Le Jugement dernier sera exécuté. La Chute des anges rebelles fut confiée à Matteo da Lecce, collaborateur de Michel-Ange, mais le projet n'aboutit pas.

La fresque s'étend sur un vaste mur de 20 mètres de haut sur 10 mètres de large, en forme de double lunette. Michel-Ange y compose une scène saisissante. À la fois ordonnée et bouillonnante, elle offre une vision torturée très éloignée de la calme majesté des représentations traditionnelles.

Pour suggérer la profondeur de l'espace, Michel-Ange choisit de peindre le fond de la scène en bleu lapis-lazuli, ce qui retarda le début des travaux car il lui fallut se procurer les pigments30 ; la figure du Christ surprend par son apparence inhabituelle de jeune homme viril et athlétique où Michel-Ange exprime la puissance divine plutôt que sa miséricorde.

À l'époque, l'œuvre fait scandale, car ses quelque quatre-cents personnages sont entièrement nus, y compris le Christ. Paul IV envisagera même de détruire la composition mais il se contentera d'en faire voiler pudiquement certains personnages par Daniele da Volterra, qui y gagnera le surnom d'il braghettone (le culottier). Au XVIIe siècle, Clément XII fera ajouter d'autres voiles. Cette entreprise se poursuivra encore en plein XXe siècle, sous le pontificat de Pie XI.

La restauration effectuée de 1981 à 1992 a permis une vision neuve de l'œuvre.
Tapisseries
Discours de Saint Paul aux Athéniens, un des cartons de Raphaël pour les tapisseries de la Sixtine, V&AM, Londres;
Articles détaillés : Cartons de Raphaël et Tapisseries de Raphaël.

Lors de cérémonies importantes, la partie inférieure des parois latérales, ornée de fresques de faux rideaux, était recouverte d'une série de dix tapisseries, réalisées par la manufacture flamande de Pieter van Aelst d'après des dessins de Raphaël. Ils reproduisent les événements des récits des principes apostolorum Pierre et Paul, tirés des Évangiles et des Actes des apôtres.

Sous les Histoires du Christ, sont disposées quatre tapisseries avec des Histoires de saint Pierre à partir de la pêche miraculeuse ; de l'autre côté, sous les Histoires de Moïse, il y avait six Histoires de saint Paul, du Martyre de Saint Etienne jusqu'au Sermon de Saint Paul aux Athéniens situé au-delà de la porte20.

Raphael, conscient de la comparaison avec Michel-Ange, a conçu des dessins au « style tragique », commencés avec l'Incendie de Borgo, simplifiant les schémas et mettant l'accent sur les gestes et les expressions faciales des personnages, pour les rendre plus significatifs et « universels »20.

Sept des dessins originaux de Raphael nous sont parvenus et sont maintenant conservés au Victoria and Albert Museum de Londres. Les tapisseries proprement dites se trouvent dans la Pinacothèque du Vatican, où elles sont exposées dans la salle VIII. Diverses répliques des tapisseries de la Sixtine ont été tirées des propres dessins de Raphaël ou de copies d'entre eux, qui sont actuellement conservées dans plusieurs lieux en Italie tels que Mantoue et Lorette.
Orgue
L'orgue.

Un orgue à tuyaux est installé dans le coin droit de la contre-façade. L'instrument a été inauguré le 14 décembre 2002 avec un concert de l'organiste Gianluca Libertucci en présence de diverses autorités vaticanes, telles que le cardinal Angelo Sodano et Mgr Piero Marini, ainsi que Hermann Mathis, directeur de Mathis Orgelbau, la société de fabrication d'orgue qui l'a construit31. L'orgue dispose de deux claviers de 56 touches chacun et d'un pédalier de 30 touches. Il est entièrement à transmission mécanique.
Choix de l'iconographie
Le leitmotiv généalogique détermine la spécificité de la Sixtine qui se veut un reflet direct des mobiles centraux de la politique papale et qui, dans le cas de Jules II et de son oncle Sixte IV, illustre aussi la politique familiale, d'orientation dynastique, des della Rovere. Michel-Ange porte à son sommet conclusif la primatue papae, c'est-à-dire sur l'autoreprésentation et la légitimation de la papauté romaine par rapport à d'autres institutions internes ou extérieures à l'Église, que traduisent déjà les portraits des papes et les histoires de Moïse et du Christ des fresques murales du XVe siècle ; de même qu'après son élection, Jules II mène à bien la politique familiale initiée par son oncle, de même, avec la commande des fresques de la voûte, Michel-Ange complète la décoration de la chapelle pontificale commencée par Sixte 
`
