let portugueseSeed = `
Almirante Barroso foi um cruzador operado pela Armada Imperial Brasileira, posteriormente Marinha do Brasil de 1882 a 1893. Seu nome de batismo é uma homenagem ao herói brasileiro Almirante Francisco Manuel Barroso da Silva. Sua construção teve início em 1880 no Arsenal de Marinha do Rio de Janeiro, sendo lançado ao mar em 1882. O navio era uma demonstração do potencial da indústria naval brasileira da época, construído com uma combinação de madeira e aço.

O Almirante Barroso possuía um deslocamento de 2 050 toneladas e uma velocidade de 12 milhas por hora. Sua artilharia incluía canhões Whitworth, metralhadoras Nordenfelt e um sistema de armamento portátil Kropatshek. A construção do navio foi um investimento substancial, totalizando 1 400 contos de réis.

Após sua incorporação à Esquadra de Evoluções em 1884, o Almirante Barroso participou de comissões de instrução e viagens ao redor do mundo, reforçando a modernização da Marinha Brasileira. No entanto, a embarcação enfrentou um momento relativamente tenso durante a queda da monarquia brasileira em 1889, quando o príncipe imperial Dom Augusto, que estava a bordo do navio, se viu envolvido na transição política.

A jornada do navio continuou com uma viagem de circum-navegação que culminou em seu retorno ao Rio de Janeiro em 1890, após uma viagem de 301 dias ao redor do mundo. O Almirante Barroso sofreu um naufrágio em 1893 devido a uma tempestade de grandes proporções no Golfo de Leão. Apesar dos esforços de resgate, o navio não pôde ser salvo, resultando em sua perda. Anos depois, mergulhadores alegaram ter encontrado os restos do navio, porém não conseguiram provar as origens do naufrágio.
História
Construção

O Almirante Barroso, foi o segundo navio na Marinha do Brasil a utilizar este nome. É uma homenagem ao Almirante Francisco Manuel Barroso da Silva, primeiro e único Barão do Amazonas.[1] As outras embarcações que homenagearam o herói brasileiro foram o encouraçado Barroso (1865), o navio cruzador Barroso (C-1) (1895), o cruzador Ligeiro Barroso (C-11) (1951) e a corveta Barroso (2008).[2] O ferro utilizado em sua construção foi produzido pela Fábrica de São José do Ipanema.[3]

O batimento de quilha do navio ocorreu no Arsenal de Marinha do Rio de Janeiro em 1.º de março de 1880. O evento de lançamento ao mar, ocorrido em 17 de abril de 1882, foi uma celebração que contou com o comparecimento do Imperador D. Pedro II, do Almirante Barroso, ministros de estado, autoridades locais e uma multidão de populares. O navio foi batizado com cerimônia e submetido à Mostra de Armamento em 19 de julho de 1882, quando recebeu o distintivo número 22. Sua construção mista, combinando madeira e aço, representava o desenvolvimento da indústria naval brasileira naquela época.[4]
Características

As especificações técnicas do navio eram: deslocamento de 2 050 toneladas, o navio apresentava um comprimento extremo de 71,25 metros, um comprimento entre perpendiculares de 64,05 metros, uma largura de 11,33 metros, um pontal de 10,97 metros e um calado médio de 6,40 metros. A máquina do navio, projetada sob os planos e supervisão do Capitão-Tenente Engenheiro Naval Manuel Alves Barbosa, com uma potência efetiva de 2 200 cavalos que permitia atingir uma velocidade de 12[4] ou 13[5] nós.[4] Além das máquinas, o cruzador tinha também como meio de propulsão velas armadas em corveta, tendo sua superfície 1 625 m².[1]

O navio estava equipado com duas caldeiras do tipo Almirantado. Além disso, possuía uma hélice e uma chaminé. O custo de construção deste navio de guerra foi substancial, totalizando 1 400 contos de réis.[4] A artilharia do navio incluía seis canhões Whitworth de calibre 70 montados em carretas Levasseur, com raiamento, dispostos em bateria à barbeta. Além disso, o navio estava equipado com um rodízio à proa em caça, quatro metralhadoras Nordenfelt de 25 mm e seis metralhadoras do mesmo tipo, mas de 11 mm. Posteriormente, o armamento portátil do navio foi atualizado com o sistema Kropatshek.[4] Sua tripulação era consistida de 285 oficiais e praças.[5] Em geral, as características do cruzador Almirante Barroso já eram ultrapassadas a contar da década anterior à sua construção,[6] apesar de representar uma evolução da indústria naval brasileira na construção deste tipo de embarcação desde o período anterior à Guerra do Paraguai (1864-1870).[7]
Comissões
Almirante Barroso em data desconhecida

Em 19 de agosto de 1884, ocorreu com a incorporação do cruzador Almirante Barroso à recém-criada Esquadra de Evoluções. Esse evento foi fruto do Aviso n.º 1541A, emitido pelo então Ministro dos Negócios da Marinha, o Almirante Joaquim Raymundo de Lamare. A Esquadra de Evoluções tinha à sua frente como primeiro comandante o Chefe-de-Esquadra Arthur Silveira da Mota, que detinha o título de Barão de Jaceguai. Composta por dezesseis navios, a esquadra se destacava pelos encouraçados Riachuelo, Sete de Setembro, Solimões e Javary, além dos cruzadores Guanabara, Trajano e Primeiro de Março. A presença das Torpedeiras de 1ª Classe 1, 2, 3, 4 e 5, juntamente com as Torpedeiras de 4ª Classe Alfa, Beta e Gama, reforçava o poder de fogo e a capacidade de manobra da frota.[1]

A Esquadra de Evoluções representava o núcleo mais moderno e avançado da Armada Brasileira daquela época. Era dotada de navios com as melhores tecnologias em termos de propulsão, artilharia e sistemas de torpedos, demonstrando o comprometimento do Brasil em manter uma força naval eficaz e capaz de se adaptar às mudanças na paisagem geopolítica. A criação da Esquadra de Evoluções também marcou o início de um período de transformação e modernização da Marinha brasileira.[1]

O comando do navio foi inicialmente confiado ao Capitão de Mar e Guerra José Marques Guimarães, que foi substituído em 1884 pelo também Capitão de Mar e Guerra Luís Filipe de Saldanha da Gama. Durante suas experiências de velocidade, o navio enfrentou um obstáculo ao encalhar nas pedras Obuzes devido ao deslocamento de uma boia de sinalização. No entanto, o navio logo provou suas capacidades de navegação após receber a ordem de "Siga seu destino," desligando-se de uma divisão e velejando para diversas localidades costeiras, como Abrolhos, Ilha Grande, Florianópolis e a região de Abraão, Santana e Angra dos Reis.[4]

O navio também empreendeu viagens de instrução, com guardas-marinha a bordo. Uma dessas comissões incluiu paradas em locais como Recife, Barbados, Jamaica, Nova Orleães e Nova Iorque, demonstrando a capacidade do navio de cruzar o Atlântico. Durante suas viagens, o navio fez escalas em várias ilhas e portos, incluindo São Miguel dos Açores, Madeira, Cabo Verde, São Vicente e São Tiago. O ano de 1888 viu o navio sendo incorporado a uma divisão que viajou pelo norte do Brasil, fazendo escalas em locais como Pernambuco, Fernando de Noronha, São Luiz e Belém do Pará. A comissão de instrução do navio continuou a ser um foco importante de suas operações, e ele logo se preparou para uma viagem de circunavegação sob o comando do Capitão de Mar e Guerra Custódio José de Mello. Em direção à sua esperada viagem de circum-navegação, o navio partiu após uma visita do Imperador D. Pedro II e da família imperial em 27 de outubro de 1888.[4]
Circum-navegação

Durante sua próxima jornada, o navio recebeu uma tripulação adicional em diferentes portos, o que não surpreendeu, dado o caráter rotineiro dessas adições. Em Montevidéu, embarcaram o Primeiro-Tenente José Augusto de Armelino e o Dr. Henrique dos Santos Reis em 5 de novembro, seguidos pelo Maquinista Nicolau José Marques em Valparaíso, em 23 de novembro. O itinerário que se seguiu abrangeu diversos continentes e cidades ao redor do mundo, mas sem eventos extraordinários. A viagem começou com uma visita a Montevidéu, onde o navio permaneceu de 5 a 12 de novembro. Em seguida, ele navegou até Buenos Aires, onde ficou de 13 a 23 de novembro. Após retornar a Montevidéu, o navio partiu novamente em 24 de novembro e chegou a Punta Arenas, onde permaneceu de 19 a 28 de dezembro. O próximo destino foi Valparaíso, onde o navio ficou ancorado de 23 de janeiro a 24 de fevereiro de 1889. A viagem continuou em direção ao leste, com o navio fazendo uma parada em Sidney, Austrália, de 8 de maio a 6 de junho. Em seguida, a rota seguiu para o Japão, com paradas em Yokohama, de 20 de julho a 4 de agosto, e Nagasaki, de 9 a 15 de agosto. O navio fez escala em Xangai, na China, de 18 a 27 de agosto, e em Hong Kong, de 1.º a 29 de setembro. A viagem prosseguiu com visitas a Singapura, onde o navio ancorou de 8 a 16 de outubro, e Batávia, de 20 a 30 de outubro.[4]
O príncipe imperial Dom Augusto em trajes típicos japoneses durante escala do Almirante Barroso no Japão, em 1889

O príncipe imperial Dom Augusto estava a bordo da embarcação durante os acontecimentos da queda da monarquia brasileira causada pelo golpe de 15 de novembro de 1889. O choque causado por essa reviravolta na política brasileira foi ampliado pela dificuldade de comunicação da época. A tripulação do Almirante Barroso só teve conhecimento dos eventos que se desenrolavam em sua terra natal em dezembro. Os telegramas recebidos do Almirante Wandenkolk, que agora ocupava o cargo de Ministro da Marinha do governo provisório, orientavam o comandante do cruzador a tomar medidas drásticas. Era necessário substituir as insígnias imperiais das bandeiras, um ato simbólico que representava o fim do regime monárquico, e, induzir Dom Augusto a pedir demissão. Diante de tal situação, o príncipe não tomou uma decisão precipitada. Ele consultou seu avô e seu tio, o conde d'Eu, ponderando cuidadosamente os passos a seguir. No entanto, em um ato de firmeza, Dom Augusto decidiu não se demitir, mas solicitar uma licença de dois meses.[8][9]

A resposta do Ministro Wandenkolk ao pedido de licença foi clara e incisiva, marcando o ponto de não retorno na vida do príncipe: "Príncipe peça demissão [do] serviço, concedo licença. Wandenkolk." O príncipe, então, desembarcou em Colombo, no Ceilão, onde a tripulação do Almirante Barroso lhe ofereceu um jantar de despedida. Esse evento foi carregado de emoção e simbolismo, representando não apenas uma separação entre o príncipe e seus companheiros de viagem, mas também o fim de uma era para a monarquia brasileira. Em um ato de generosidade, Dom Augusto distribuiu seus pertences entre seus companheiros.[8]

A viagem prosseguiu com paragens em Oleh Leh, de 30 de novembro a 7 de dezembro, Colombo, de 13 a 23 de dezembro, e Bombaim, onde o navio permaneceu de 30 de dezembro de 1889 a 22 de fevereiro de 1890. Durante essa jornada, houve uma alteração na liderança da embarcação. Com a promoção do Comandante do navio, Capitão de Mar e Guerra Custódio de Melo, a Contra-Almirante, ele transferiu o comando ao Capitão de Mar e Guerra Joaquim Marques Batista de Leão. A viagem continuou com paragens em Jidá, de 5 a 8 de março, Suez, de 22 a 23 de março, Port Said, de 24 a 25 de março, Alexandria, de 26 de março a 7 de abril, Nápoles, de 15 a 24 de abril, Toulon, de 28 de abril a 18 de maio, Barcelona, de 19 de maio a 2 de junho, Gibraltar, de 5 a 9 de junho, e Bahia, de 9 a 28 de julho. A viagem culminou com a chegada ao Rio de Janeiro no dia 29 de junho de 1890, às 10h30 da manhã. Após 301 dias e 7 horas de navegação, o navio percorreu um total de 17 965 milhas a vapor e 17 507 milhas a vela. Em meados de 1890, a embarcação preparava-se para outra viagem de circum-navegação, demonstrando sua importância contínua na marinha brasileira e seu compromisso com a exploração e projeção de poder em escala global.[4]
Naufrágio
Desenho do Almirante Barroso em alto mar

Após deixar Toulon, o navio enfrentou um terrível revés em 20 de janeiro de 1893, quando um violento temporal atingiu o Golfo de Leão, causando graves danos à embarcação. Diante da extensão das avarias, o navio precisava retornar ao Porto de Toulon para passar por reparos substanciais. Após as necessárias reparações, o navio embarcou sua tripulação anterior, com exceção de um Primeiro-Tenente, e continuou a viagem. Adentrando o Mar Vermelho, o navio navegou adiante até estar aproximadamente a 120 milhas de Suez. Nesse momento, já afastado cerca de 30 milhas ao sul do farol de Ras Gharib, em frente à Praia de Zeiti, no Estreito de Jubal, um evento dramático ocorreu. Na madrugada de 21 de maio de 1893, por volta de 1h30, o navio encalhou em um banco de corais, e não pôde ser salvo.[4]

Segundo o Primeiro-Tenente Felinto Perry, que estava a bordo, o navio estava navegando a toda velocidade, e ele estava na praça d'armas, organizando observações meteorológicas em um livro. Logo após deitar-se, o navio sofreu uma colisão, causando estremecimentos. Perry percebeu que algo sério estava acontecendo quando sentiu choques mais fortes e ouviu vozes de manobra e passos apressados a bordo. Ele se vestiu rapidamente e foi para a tolda, onde encontrou o comandante e outros oficiais já envolvidos na tentativa de salvar o navio. O navio estava encalhado e sendo empurrado contra pedras pela arrebentação. Uma tentativa de lançar um escaler com uma tripulação inadequada foi difícil e não teve sucesso. Perry decidiu tentar levar um ancorote para ajudar na situação. Ele pulou em um escaler com o objetivo de convencer os outros de que era impossível trazer o ancorote devido às condições perigosas do mar. Enquanto tentavam se aproximar da embarcação com o ancorote, uma onda grande ameaçou virar o escaler. O autor cortou o cabo que prendia o ancorote, aliviando o peso da embarcação e evitando o naufrágio iminente.[10] A situação tornou-se trágica, pois, durante os esforços para resgatar um membro da tripulação, o Ajudante de Máquinas Tancredo J. Alves perdeu a vida, tentando salvar um de seus colegas.[4]

A tripulação ficou presa durante três dias na praia de Zeiti, em meio a circunstâncias difíceis. O resgate ficou a cargo da canhoneira inglesa Dolphin, comandada pelo oficial Cradock. A ação corajosa do comandante inglês e sua tripulação foi fundamental para salvar vidas e garantir a segurança dos marinheiros brasileiros.[4] Após os procedimentos de salvamento serem realizados, o Almirante Barroso permaneceu durante um tempo na superfície ainda que preso aos corais. Saqueadores beduinos aproveitaram que a embarcação estava à mercê e pilharam completamente o navio. Essa situação levantou controvérsias sobre um prático que guiava o caminho da embarcação desde o Golfo de Leão. Levantou-se a acusação que esse prático estaria de conluio com algum chefe tribal dos beduinos. No entanto, nada foi provado contra o próprio que acabou absolvido de qualquer acusação.[11] Uma investigação foi iniciada no Conselho de Guerra da marinha para apurar a responsabilização do comandante Joaquim Marques Batista de Leão, porém ele também acabou por ser absolvido.[12] Cerca de 125 anos depois, em fevereiro de 2018, um grupo de mergulhadores do Sea Red Explorers alegou ter supostamente encontrado os restos do cruzador em uma expedição submarina no Estreito de Gubal, a aproximadamente cinco quilômetros ao norte de uma ilha costeira. Submerso entre 62 e 73 metros de profundidade, repousava o suposto cruzador naufragado, apoiado na areia do leito oceânico. Embora a equipe de pesquisadores admita que ainda não há uma comprovação total das origens do naufrágio, as medidas, características e a localização coincidem com dados históricos registrados.
`